// frontend/src/pages/groups/GroupVendorGroupIdsTab.tsx
// Component for viewing and managing vendor-specific Group IDs for a group

import React, { useEffect, useState } from 'react';
import {
  FileDown,
  FileSignature,
  Plus, 
  Edit, 
  Trash2, 
  RefreshCw, 
  CheckCircle, 
  Package,
  Tag,
  Wand2,
  X,
  MapPin,
  ToggleLeft,
  ToggleRight
} from 'lucide-react';
import { apiService } from '../../services/api.service';
import { useAuth } from '../../contexts/AuthContext';
import NewGroupFormCertificationSignModal from '../../components/groups/NewGroupFormCertificationSignModal';
import { useGroupVendorLocationIdSetting } from '../../hooks/admin/useGroupVendorLocationIdSetting';
import { useGroupLocationVendorIds, GeneratePreviewItem, LocationVendorId } from '../../hooks/admin/useGroupLocationVendorIds';

interface GroupVendorGroupId {
  VendorGroupId: string;
  ProductType: string | null;
  GroupProductId: string | null;
  ProductId: string | null;
  ProductName: string;
  IsAutoGenerated: boolean;
  GroupId?: string;
}

interface Vendor {
  VendorId?: string; // Some APIs return VendorId
  Id?: string; // Vendors API returns Id (mapped from VendorId)
  VendorName: string;
}

interface GroupVendorGroupIdsTabProps {
  groupId: string;
  groupName: string;
  /** Opens the Generate New Group Form modal (in parent GroupDetails) */
  onOpenNewGroupForm?: () => void;
}

// ─── Location vendor group IDs section ───────────────────────────────────────

interface LocationVendorGroupIdsSectionProps {
  groupId: string;
  vendorId: string;
  vendorName: string;
  canEdit: boolean;
}

const LocationVendorGroupIdsSection: React.FC<LocationVendorGroupIdsSectionProps> = ({
  groupId,
  vendorId,
  vendorName,
  canEdit,
}) => {
  const { enabled, loading: settingLoading, saving: settingSaving, toggle } =
    useGroupVendorLocationIdSetting(groupId, vendorId);

  const { locationIds, loading: idsLoading, refresh, previewGenerate, applyGenerate, updateLocationId } =
    useGroupLocationVendorIds(groupId, vendorId);

  const [showGenerateModal, setShowGenerateModal] = useState(false);
  const [generatePreview, setGeneratePreview] = useState<GeneratePreviewItem[]>([]);
  const [generateLoading, setGenerateLoading] = useState(false);
  const [generateApplying, setGenerateApplying] = useState(false);

  const [editingLocationId, setEditingLocationId] = useState<string | null>(null);
  const [editValue, setEditValue] = useState('');
  const [editSaving, setEditSaving] = useState(false);

  const handleGenerateClick = async () => {
    setGenerateLoading(true);
    try {
      const preview = await previewGenerate();
      setGeneratePreview(preview);
      setShowGenerateModal(true);
    } catch (err: unknown) {
      const msg = (err as { response?: { data?: { message?: string } } })?.response?.data?.message
        || (err as Error)?.message
        || 'Failed to load preview';
      alert(msg);
    } finally {
      setGenerateLoading(false);
    }
  };

  const handleGenerateConfirmApply = async () => {
    setGenerateApplying(true);
    try {
      const result = await applyGenerate();
      setShowGenerateModal(false);
      setGeneratePreview([]);
      const parts: string[] = [];
      if (result.created > 0) parts.push(`Created ${result.created} location vendor ID(s)`);
      if (result.created === 0) parts.push('No new location vendor IDs to create');
      alert(parts.join('; ') + (result.errors.length ? '\nIssues:\n' + result.errors.join('\n') : ''));
    } catch (err: unknown) {
      const msg = (err as { response?: { data?: { message?: string } } })?.response?.data?.message
        || (err as Error)?.message
        || 'Failed to apply';
      alert(msg);
    } finally {
      setGenerateApplying(false);
    }
  };

  const handleEditSave = async () => {
    if (!editingLocationId) return;
    setEditSaving(true);
    try {
      await updateLocationId(editingLocationId, editValue.trim());
      setEditingLocationId(null);
      setEditValue('');
    } catch (err: unknown) {
      const msg = (err as { response?: { data?: { message?: string } } })?.response?.data?.message
        || (err as Error)?.message
        || 'Failed to save';
      alert(msg);
    } finally {
      setEditSaving(false);
    }
  };

  if (settingLoading) {
    return (
      <div className="mt-8 pt-6 border-t border-gray-200">
        <div className="flex items-center gap-2 text-gray-500 text-sm">
          <RefreshCw className="h-4 w-4 animate-spin" />
          Loading location vendor ID settings…
        </div>
      </div>
    );
  }

  return (
    <div className="mt-8 pt-6 border-t border-gray-200">
      {/* Section header + toggle */}
      <div className="flex items-start justify-between gap-4 mb-4">
        <div>
          <h3 className="text-lg font-medium text-gray-900 flex items-center gap-2">
            <MapPin className="h-5 w-5 text-gray-400" />
            Location Vendor Group IDs
          </h3>
          <p className="text-sm text-gray-600 mt-1">
            Assign per-location vendor IDs for {vendorName}. Enable to generate or manually set an ID per location.
          </p>
        </div>
        {canEdit && (
          <button
            type="button"
            onClick={() => toggle(!enabled)}
            disabled={settingSaving}
            className="flex items-center gap-2 px-3 py-1.5 text-sm rounded-lg border border-gray-300 text-gray-700 hover:bg-gray-50 disabled:opacity-50 shrink-0"
          >
            {enabled ? (
              <ToggleRight className="h-5 w-5 text-oe-primary" />
            ) : (
              <ToggleLeft className="h-5 w-5 text-gray-400" />
            )}
            {settingSaving ? 'Saving…' : enabled ? 'Enabled' : 'Disabled'}
          </button>
        )}
      </div>

      {!enabled && (
        <p className="text-sm text-gray-500">
          Enable location vendor group IDs to assign individual vendor IDs to each location in this group.
        </p>
      )}

      {enabled && (
        <>
          {/* Actions */}
          <div className="mb-4 flex items-center justify-end gap-2">
            <button
              onClick={() => refresh()}
              className="flex items-center px-3 py-1.5 text-sm border border-gray-300 text-gray-700 rounded-lg hover:bg-gray-50"
            >
              <RefreshCw className="h-4 w-4 mr-1" />
              Refresh
            </button>
            {canEdit && (
              <button
                onClick={handleGenerateClick}
                disabled={generateLoading}
                className="flex items-center px-4 py-2 border border-gray-300 text-gray-700 rounded-lg hover:bg-gray-50 disabled:opacity-50"
              >
                {generateLoading ? (
                  <RefreshCw className="h-4 w-4 mr-2 animate-spin" />
                ) : (
                  <Wand2 className="h-4 w-4 mr-2" />
                )}
                Generate location IDs
              </button>
            )}
          </div>

          {/* Location IDs table */}
          {idsLoading ? (
            <div className="flex items-center justify-center py-8">
              <RefreshCw className="h-5 w-5 animate-spin text-gray-400" />
              <span className="ml-2 text-gray-600 text-sm">Loading…</span>
            </div>
          ) : locationIds.length === 0 ? (
            <div className="bg-gray-50 border border-gray-200 rounded-lg p-6 text-center">
              <MapPin className="h-10 w-10 text-gray-400 mx-auto mb-3" />
              <p className="text-gray-600 text-sm mb-1">No location vendor IDs found</p>
              <p className="text-xs text-gray-500">
                Use &quot;Generate location IDs&quot; to create them, or add them manually.
              </p>
            </div>
          ) : (
            <div className="bg-white border border-gray-200 rounded-lg overflow-hidden">
              <table className="min-w-full divide-y divide-gray-200">
                <thead className="bg-gray-50">
                  <tr>
                    <th className="px-5 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      Location
                    </th>
                    <th className="px-5 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      Vendor Location ID
                    </th>
                    <th className="px-5 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      Type
                    </th>
                    {canEdit && (
                      <th className="px-5 py-3 text-right text-xs font-medium text-gray-500 uppercase tracking-wider">
                        Actions
                      </th>
                    )}
                  </tr>
                </thead>
                <tbody className="bg-white divide-y divide-gray-200">
                  {locationIds.map((item: LocationVendorId) => (
                    <tr key={item.LocationId} className="hover:bg-gray-50">
                      <td className="px-5 py-3 whitespace-nowrap text-sm text-gray-900">
                        {item.LocationName || item.LocationId}
                      </td>
                      <td className="px-5 py-3 whitespace-nowrap">
                        {editingLocationId === item.LocationId ? (
                          <input
                            type="text"
                            value={editValue}
                            onChange={(e) => setEditValue(e.target.value)}
                            className="px-2 py-1 border border-gray-300 rounded focus:ring-2 focus:ring-oe-primary text-sm"
                            autoFocus
                          />
                        ) : (
                          <div className="flex items-center gap-2">
                            <Tag className="h-4 w-4 text-gray-400" />
                            <span className="text-sm font-medium text-gray-900">
                              {item.VendorLocationId ?? '—'}
                            </span>
                          </div>
                        )}
                      </td>
                      <td className="px-5 py-3 whitespace-nowrap">
                        {item.VendorLocationId ? (
                          item.IsAutoGenerated ? (
                            <span className="inline-flex items-center px-2 py-0.5 rounded-full text-xs font-semibold bg-oe-light text-oe-primary">
                              <CheckCircle className="h-3 w-3 mr-1" />
                              Auto
                            </span>
                          ) : (
                            <span className="inline-flex items-center px-2 py-0.5 rounded-full text-xs font-semibold bg-gray-100 text-gray-700">
                              Manual
                            </span>
                          )
                        ) : (
                          <span className="text-xs text-gray-400">Pending</span>
                        )}
                      </td>
                      {canEdit && (
                        <td className="px-5 py-3 whitespace-nowrap text-right text-sm">
                          {editingLocationId === item.LocationId ? (
                            <div className="flex items-center justify-end gap-2">
                              <button
                                onClick={handleEditSave}
                                disabled={editSaving}
                                className="px-3 py-1 text-xs text-white rounded-md disabled:opacity-50 bg-oe-primary hover:bg-oe-dark"
                              >
                                {editSaving ? 'Saving…' : 'Save'}
                              </button>
                              <button
                                onClick={() => { setEditingLocationId(null); setEditValue(''); }}
                                className="px-3 py-1 text-xs border border-gray-300 text-gray-700 rounded-md hover:bg-gray-50"
                              >
                                Cancel
                              </button>
                            </div>
                          ) : (
                            <button
                              onClick={() => {
                                setEditingLocationId(item.LocationId);
                                setEditValue(item.VendorLocationId ?? '');
                              }}
                              className="text-oe-primary hover:text-blue-900"
                              title="Edit vendor location ID"
                            >
                              <Edit className="h-4 w-4" />
                            </button>
                          )}
                        </td>
                      )}
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </>
      )}

      {/* Generate modal */}
      {showGenerateModal && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50">
          <div className="bg-white rounded-lg max-w-2xl w-full max-h-[90vh] flex flex-col">
            <div className="p-6 border-b border-gray-200 flex items-center justify-between">
              <h3 className="text-lg font-semibold text-gray-900">Generate location IDs – Preview</h3>
              <button
                onClick={() => { setShowGenerateModal(false); setGeneratePreview([]); }}
                className="p-1 rounded hover:bg-gray-100 text-gray-500"
                aria-label="Close"
              >
                <X className="h-5 w-5" />
              </button>
            </div>
            <div className="p-6 overflow-auto flex-1">
              {generatePreview.length === 0 ? (
                <p className="text-gray-600 text-sm">No locations need new vendor IDs, or none are configured for this vendor.</p>
              ) : (
                <table className="min-w-full divide-y divide-gray-200">
                  <thead className="bg-gray-50">
                    <tr>
                      <th className="px-4 py-2 text-left text-xs font-medium text-gray-500 uppercase">Location</th>
                      <th className="px-4 py-2 text-left text-xs font-medium text-gray-500 uppercase">Proposed ID</th>
                      <th className="px-4 py-2 text-left text-xs font-medium text-gray-500 uppercase">Status</th>
                    </tr>
                  </thead>
                  <tbody className="bg-white divide-y divide-gray-200">
                    {generatePreview.map((row: GeneratePreviewItem) => (
                      <tr key={row.LocationId}>
                        <td className="px-4 py-2 text-sm text-gray-900">{row.LocationName}</td>
                        <td className="px-4 py-2 text-sm font-medium text-gray-900">{row.proposedVendorLocationId}</td>
                        <td className="px-4 py-2 text-sm">
                          {row.idInUse ? (
                            <span className="text-amber-600">ID in use elsewhere</span>
                          ) : row.alreadyExists ? (
                            <span className="text-gray-500">Existing</span>
                          ) : (
                            <span className="text-green-600">To create</span>
                          )}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              )}
            </div>
            {generatePreview.length > 0 && generatePreview.every((p) => p.alreadyExists) && (
              <div className="px-6 py-3 bg-gray-50 border-t border-gray-200 text-sm text-gray-600">
                All locations already have vendor IDs. Nothing to create.
              </div>
            )}
            <div className="p-6 border-t border-gray-200 flex justify-end gap-2">
              <button
                onClick={() => { setShowGenerateModal(false); setGeneratePreview([]); }}
                className="px-4 py-2 border border-gray-300 text-gray-700 rounded-lg hover:bg-gray-50"
              >
                Cancel
              </button>
              <button
                onClick={handleGenerateConfirmApply}
                disabled={generateApplying || generatePreview.length === 0 || generatePreview.every((p) => p.alreadyExists)}
                className="px-4 py-2 text-white rounded-lg disabled:opacity-50 bg-oe-primary hover:bg-oe-dark"
              >
                {generateApplying ? 'Applying…' : 'Confirm & Apply'}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

// ─────────────────────────────────────────────────────────────────────────────

const GroupVendorGroupIdsTab: React.FC<GroupVendorGroupIdsTabProps> = ({ groupId, onOpenNewGroupForm }) => {
  const { user } = useAuth();
  const [vendors, setVendors] = useState<Vendor[]>([]);
  const [selectedVendorId, setSelectedVendorId] = useState<string>('');
  const [groupIds, setGroupIds] = useState<GroupVendorGroupId[]>([]);
  const [loading, setLoading] = useState(false);
  const [vendorsLoading, setVendorsLoading] = useState(false);
  const [showAddModal, setShowAddModal] = useState(false);
  const [showEditModal, setShowEditModal] = useState(false);
  const [editingGroupId, setEditingGroupId] = useState<GroupVendorGroupId | null>(null);
  const [availableProducts, setAvailableProducts] = useState<any[]>([]);
  const [showGenerateModal, setShowGenerateModal] = useState(false);
  const [generatePreview, setGeneratePreview] = useState<Array<{ groupProductId: string; productName: string; vendorId: string; vendorName: string; productType: string; vendorGroupId: string; alreadyExists: boolean; idInUse?: boolean; sharesWithFallback?: boolean; sharesWithProductName?: string | null }>>([]);
  const [generateLoading, setGenerateLoading] = useState(false);
  const [generateApplying, setGenerateApplying] = useState(false);

  // New Group Form certification (agent + group admin signatures)
  const [certification, setCertification] = useState<{
    agentSignedAt: string | null;
    agentHasSignature: boolean;
    groupAdminSignedAt: string | null;
    groupAdminHasSignature: boolean;
    signaturesRequired?: boolean;
  } | null>(null);
  const [certificationLoading, setCertificationLoading] = useState(false);
  const [signModalRole, setSignModalRole] = useState<'agent' | 'group-admin' | null>(null);
  const [signSubmitting, setSignSubmitting] = useState(false);
  
  // Check if user has write permissions (SysAdmin or TenantAdmin only)
  const canEdit = user?.currentRole === 'SysAdmin' || user?.currentRole === 'TenantAdmin';
  
  // Form state for add/edit
  const [formData, setFormData] = useState({
    groupProductId: '',
    vendorId: '',
    vendorGroupId: '',
    productType: ''
  });
  
  // Track if product type is Master (to conditionally show/hide product dropdown)
  const isMasterType = formData.productType === 'Master';

  const canSignAsAgent =
    user?.currentRole === 'Agent' ||
    user?.currentRole === 'SysAdmin' ||
    user?.currentRole === 'TenantAdmin';
  const canSignAsGroupAdmin =
    user?.currentRole === 'GroupAdmin' ||
    user?.currentRole === 'SysAdmin' ||
    user?.currentRole === 'TenantAdmin';

  const fetchCertification = async () => {
    if (!groupId) return;
    setCertificationLoading(true);
    try {
      const res = await apiService.get<{ success: boolean; data?: typeof certification }>(`/api/groups/${groupId}/new-group-form/certification`);
      if (res?.success && res.data) setCertification(res.data);
      else setCertification(null);
    } catch {
      setCertification(null);
    } finally {
      setCertificationLoading(false);
    }
  };

  useEffect(() => {
    if (groupId) fetchCertification();
  }, [groupId]);

  const handleCertificationSign = async (signatureData: string) => {
    if (!groupId || !signModalRole) return;
    setSignSubmitting(true);
    try {
      const path = signModalRole === 'agent'
        ? `/api/groups/${groupId}/new-group-form/certification/agent`
        : `/api/groups/${groupId}/new-group-form/certification/group-admin`;
      await apiService.post(path, { signatureData });
      await fetchCertification();
      setSignModalRole(null);
    } catch (err: unknown) {
      const msg = (err as { response?: { data?: { message?: string }; status?: number } })?.response?.data?.message || (err as Error)?.message || 'Failed to save signature';
      alert(msg);
    } finally {
      setSignSubmitting(false);
    }
  };

  const formatCertDate = (iso: string | null) => {
    if (!iso) return null;
    try {
      const d = new Date(iso);
      return d.toLocaleDateString(undefined, { dateStyle: 'medium' });
    } catch {
      return iso;
    }
  };

  // Fetch vendors for this group from the vendor-group-ids API so the dropdown loads independently of other tabs
  useEffect(() => {
    if (!groupId) return;
    let cancelled = false;
    const load = async () => {
      setVendorsLoading(true);
      try {
        const response = await apiService.get<{ success: boolean; data: Vendor[] }>(`/api/vendor-group-ids/group/${groupId}/vendors`);
        if (cancelled) return;
        if (response && response.success && response.data) {
          const normalizedVendors = response.data.map(v => {
            const vendorId = v.Id || v.VendorId;
            return {
              ...v,
              Id: vendorId,
              VendorId: vendorId,
              VendorName: v.VendorName
            };
          });
          setVendors(normalizedVendors);
        } else if (Array.isArray(response)) {
          const normalizedVendors = response.map(v => {
            const vendorId = v.Id || v.VendorId;
            return {
              ...v,
              Id: vendorId,
              VendorId: vendorId,
              VendorName: v.VendorName
            };
          });
          setVendors(normalizedVendors);
        } else {
          setVendors([]);
        }
      } catch (error: any) {
        if (!cancelled) {
          console.error('❌ Error fetching vendors:', error);
          setVendors([]);
        }
      } finally {
        if (!cancelled) setVendorsLoading(false);
      }
    };
    load();
    return () => { cancelled = true; };
  }, [groupId]);

  // Fetch Group IDs when vendor is selected
  useEffect(() => {
    if (selectedVendorId && groupId) {
      fetchGroupIds(selectedVendorId);
    } else {
      setGroupIds([]);
    }
  }, [selectedVendorId, groupId]);

  const fetchGroupIds = async (vendorId: string) => {
    try {
      setLoading(true);
      const response = await apiService.get<{ success: boolean; data: GroupVendorGroupId[] }>(
        `/api/vendor-group-ids/group/${groupId}/vendor/${vendorId}`
      );
      console.log('🔍 fetchGroupIds response:', response);
      // apiService.get returns response.data directly, so response is already unwrapped
      if (response && response.success && response.data) {
        console.log('✅ Setting Group IDs:', response.data);
        setGroupIds(response.data);
      } else if (Array.isArray(response)) {
        // Handle case where API returns array directly
        console.log('✅ Setting Group IDs (array):', response);
        setGroupIds(response);
      } else {
        console.warn('⚠️ No Group IDs found in response:', response);
        setGroupIds([]);
      }
    } catch (error: any) {
      console.error('❌ Error fetching Group IDs:', error);
      console.error('Error details:', error.response?.data || error.message);
      setGroupIds([]);
    } finally {
      setLoading(false);
    }
  };

  const fetchGroupProducts = async () => {
    try {
      const response = await apiService.get<{ success: boolean; data: { groupProducts?: any[] } }>(
        `/api/groups/${groupId}/products`
      );
      // apiService.get returns response.data directly
      if (response && response.success && response.data) {
        // Handle both direct array and object with groupProducts property
        const products = Array.isArray(response.data) 
          ? response.data 
          : (response.data.groupProducts || []);
        setAvailableProducts(products);
      } else if (Array.isArray(response)) {
        setAvailableProducts(response);
      }
    } catch (error: any) {
      console.error('Error fetching group products:', error);
      console.error('Error details:', error.response?.data || error.message);
    }
  };

  const handleAdd = () => {
    setFormData({
      groupProductId: '',
      vendorId: selectedVendorId || '',
      vendorGroupId: '',
      productType: ''
    });
    fetchGroupProducts();
    setShowAddModal(true);
  };

  const handleGenerateClick = async () => {
    try {
      setGenerateLoading(true);
      const url = selectedVendorId
        ? `/api/vendor-group-ids/group/${groupId}/generate?vendorId=${encodeURIComponent(selectedVendorId)}`
        : `/api/vendor-group-ids/group/${groupId}/generate`;
      const response = await apiService.get<{ success: boolean; message?: string; data: typeof generatePreview }>(url);
      if (response?.success && Array.isArray(response.data)) {
        setGeneratePreview(response.data);
        setShowGenerateModal(true);
      } else {
        alert(response?.message || 'Failed to load preview');
      }
    } catch (error: any) {
      console.error('Error loading generate preview:', error);
      alert(error.response?.data?.message || error.message || 'Failed to load preview');
    } finally {
      setGenerateLoading(false);
    }
  };

  const handleGenerateConfirmApply = async () => {
    try {
      setGenerateApplying(true);
      const body = selectedVendorId ? { vendorId: selectedVendorId } : {};
      const response = await apiService.post<{
        success: boolean;
        message?: string;
        data?: { created: number; errors: string[]; deactivatedAutoUntyped?: number };
      }>(`/api/vendor-group-ids/group/${groupId}/generate`, body);
      if (response?.success) {
        setShowGenerateModal(false);
        setGeneratePreview([]);
        if (selectedVendorId) fetchGroupIds(selectedVendorId);
        const created = response.data?.created ?? 0;
        const removed = response.data?.deactivatedAutoUntyped ?? 0;
        const errors = response.data?.errors ?? [];
        let msgParts: string[] = [];
        if (created > 0) msgParts.push(`Created ${created} vendor group ID(s)`);
        if (removed > 0) msgParts.push(`removed ${removed} auto product row(s) with no VendorGroupIdProductType on the product`);
        if (created === 0 && removed === 0) msgParts.push('No database changes.');
        alert(msgParts.join('; ') + (errors.length ? '\nIssues:\n' + errors.join('\n') : ''));
      } else {
        alert(response?.message || 'Failed to create group IDs');
      }
    } catch (error: any) {
      console.error('Error applying generate:', error);
      alert(error.response?.data?.message || error.message || 'Failed to create group IDs');
    } finally {
      setGenerateApplying(false);
    }
  };
  
  const handleProductTypeChange = (newProductType: string) => {
    setFormData({
      ...formData,
      productType: newProductType,
      // Clear product selection if switching to Master
      groupProductId: newProductType === 'Master' ? '' : formData.groupProductId
    });
  };

  const handleEdit = (groupVendorGroupId: GroupVendorGroupId) => {
    setEditingGroupId(groupVendorGroupId);
    setFormData({
      groupProductId: groupVendorGroupId.GroupProductId || '',
      vendorId: selectedVendorId || '',
      vendorGroupId: groupVendorGroupId.VendorGroupId,
      productType: groupVendorGroupId.ProductType || ''
    });
    setShowEditModal(true);
  };

  const handleDelete = async (item: GroupVendorGroupId) => {
    if (!confirm('Are you sure you want to delete this Group ID?')) {
      return;
    }

    try {
      let response;
      // For Master Group IDs: use group-level endpoint
      if (item.ProductType === 'Master' && !item.GroupProductId) {
        response = await apiService.delete<{ success: boolean; message?: string }>(
          `/api/vendor-group-ids/group/${groupId}/vendor/${selectedVendorId}/master`
        );
      } else {
        // For product-specific Group IDs
        if (!item.GroupProductId) {
          alert('Cannot delete: GroupProductId is missing');
          return;
        }
        response = await apiService.delete<{ success: boolean; message?: string }>(
          `/api/vendor-group-ids/group-product/${item.GroupProductId}/vendor/${selectedVendorId}`
        );
      }
      
      // apiService.delete returns response.data directly
      if (response && response.success) {
        fetchGroupIds(selectedVendorId);
      } else {
        alert(response?.message || 'Failed to delete Group ID');
      }
    } catch (error: any) {
      console.error('Error deleting Group ID:', error);
      const errorMessage = error.response?.data?.message || error.message || 'Failed to delete Group ID';
      alert(errorMessage);
    }
  };

  // Helper to validate GUID format
  const isValidGuid = (str: string): boolean => {
    const guidRegex = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
    return guidRegex.test(str);
  };

  const handleSave = async () => {
    try {
      if (showAddModal) {
        // Validate required fields
        if (!formData.vendorGroupId || !formData.productType) {
          alert('Please fill in all required fields');
          return;
        }
        
        // Validate vendorId is a GUID, not a name
        if (!selectedVendorId || !isValidGuid(selectedVendorId)) {
          alert('Please select a valid vendor');
          console.error('Invalid vendorId:', selectedVendorId);
          return;
        }
        
        // For product-specific Group IDs, validate product is selected
        if (formData.productType !== 'Master' && !formData.groupProductId) {
          alert('Please select a product for non-Master Group IDs');
          return;
        }
        
        // Create new Group ID
        const payload: any = {
          vendorId: selectedVendorId,
          vendorGroupId: formData.vendorGroupId,
          productType: formData.productType
        };
        
        // For Master Group IDs: send groupId, no groupProductId
        if (formData.productType === 'Master') {
          payload.groupId = groupId;
          payload.groupProductId = null;
        } else {
          // For product-specific Group IDs: send groupProductId
          if (formData.groupProductId) {
            payload.groupProductId = formData.groupProductId;
          }
        }
        
        console.log('Creating Group ID with payload:', payload);
        const response = await apiService.post<{ success: boolean; message?: string }>(
          '/api/vendor-group-ids',
          payload
        );
        
        // apiService.post returns response.data directly
        if (response && response.success) {
          setShowAddModal(false);
          setFormData({ groupProductId: '', vendorId: '', vendorGroupId: '', productType: '' });
          fetchGroupIds(selectedVendorId);
        } else {
          alert(response?.message || 'Failed to create Group ID');
        }
      } else if (showEditModal && editingGroupId) {
        // Validate required fields
        if (!formData.vendorGroupId) {
          alert('Please enter a Group ID');
          return;
        }
        
        // Update existing Group ID
        // For Master Group IDs, use group-level endpoint
        if (editingGroupId.ProductType === 'Master' && !editingGroupId.GroupProductId) {
          const response = await apiService.put<{ success: boolean; message?: string }>(
            `/api/vendor-group-ids/group/${groupId}/vendor/${selectedVendorId}/master`,
            { vendorGroupId: formData.vendorGroupId }
          );
          if (response && response.success) {
            setShowEditModal(false);
            setEditingGroupId(null);
            fetchGroupIds(selectedVendorId);
          } else {
            alert(response?.message || 'Failed to update Group ID');
          }
        } else {
          // For product-specific Group IDs
          if (!editingGroupId.GroupProductId) {
            alert('Cannot update: GroupProductId is missing');
            return;
          }
          const response = await apiService.put<{ success: boolean; message?: string }>(
            `/api/vendor-group-ids/group-product/${editingGroupId.GroupProductId}/vendor/${selectedVendorId}`,
            { vendorGroupId: formData.vendorGroupId }
          );
          if (response && response.success) {
            setShowEditModal(false);
            setEditingGroupId(null);
            fetchGroupIds(selectedVendorId);
          } else {
            alert(response?.message || 'Failed to update Group ID');
          }
        }
      }
    } catch (error: any) {
      console.error('Error saving Group ID:', error);
      const errorMessage = error.response?.data?.message || error.message || 'Failed to save Group ID';
      alert(errorMessage);
    }
  };

  const selectedVendor = vendors.find(v => (v.VendorId || v.Id) === selectedVendorId);

  return (
    <div className="p-6">
      <div className="mb-6 flex flex-wrap items-start justify-between gap-4">
        <div>
          <h2 className="text-2xl font-semibold text-gray-900 mb-2">Vendors</h2>
          <p className="text-gray-600">
            View and manage vendor-specific Group IDs for products in this group. Generate new group forms for vendors with a form configured.
          </p>
        </div>
        {onOpenNewGroupForm && (
          <button
            type="button"
            onClick={onOpenNewGroupForm}
            className="flex items-center px-4 py-2 border-2 rounded-lg font-medium transition-colors shrink-0 hover:bg-gray-50"
            style={{
              borderColor: 'var(--oe-primary)',
              color: 'var(--oe-primary)',
            }}
          >
            <FileDown className="h-4 w-4 mr-2" />
            Generate New Group Form
          </button>
        )}
      </div>

      {/* Group Info Confirmation — only when at least one vendor form for this group has signature fields */}
      {certification?.signaturesRequired === true && (
      <div className="mb-6 p-4 bg-gray-50 rounded-lg border border-gray-200">
        <h3 className="text-sm font-semibold text-gray-900 mb-3 flex items-center gap-2">
          <FileSignature className="h-4 w-4" />
          Group Info Confirmation
        </h3>
        <p className="text-sm text-gray-600 mb-4">
          Sign to certify that the group information in the generated document is accurate and correct. Each role can sign from their portal; the document will show both signatures and dates when generated. Your signature is reused for all vendor forms that require it (one sign covers every vendor).
        </p>
        {certificationLoading ? (
          <p className="text-sm text-gray-500">Loading…</p>
        ) : (
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div className="flex flex-wrap items-center justify-between gap-2 p-3 bg-white rounded border border-gray-200">
              <span className="text-sm font-medium text-gray-700">Agent Signature</span>
              <div className="flex items-center gap-2">
                {certification?.agentHasSignature ? (
                  <span className="text-sm text-green-700">
                    Signed {formatCertDate(certification.agentSignedAt) ?? ''}
                  </span>
                ) : (
                  <span className="text-sm text-gray-500">Not signed</span>
                )}
                {canSignAsAgent && (
                  <button
                    type="button"
                    onClick={() => setSignModalRole('agent')}
                    className="px-3 py-1.5 text-sm rounded-lg border border-gray-300 text-gray-700 hover:bg-gray-50"
                  >
                    {certification?.agentHasSignature ? 'Re-sign' : 'Sign'}
                  </button>
                )}
              </div>
            </div>
            <div className="flex flex-wrap items-center justify-between gap-2 p-3 bg-white rounded border border-gray-200">
              <span className="text-sm font-medium text-gray-700">Group Admin Signature</span>
              <div className="flex items-center gap-2">
                {certification?.groupAdminHasSignature ? (
                  <span className="text-sm text-green-700">
                    Signed {formatCertDate(certification.groupAdminSignedAt) ?? ''}
                  </span>
                ) : (
                  <span className="text-sm text-gray-500">Not signed</span>
                )}
                {canSignAsGroupAdmin && (
                  <button
                    type="button"
                    onClick={() => setSignModalRole('group-admin')}
                    className="px-3 py-1.5 text-sm rounded-lg border border-gray-300 text-gray-700 hover:bg-gray-50"
                  >
                    {certification?.groupAdminHasSignature ? 'Re-sign' : 'Sign'}
                  </button>
                )}
              </div>
            </div>
          </div>
        )}
      </div>
      )}

      {signModalRole && (
        <NewGroupFormCertificationSignModal
          title={signModalRole === 'agent' ? 'Agent Signature' : 'Group Admin Signature'}
          onConfirm={handleCertificationSign}
          onClose={() => setSignModalRole(null)}
          loading={signSubmitting}
        />
      )}

      {/* Vendor Selection (only vendors that have products in this group) */}
      <div className="mb-6">
        <label className="block text-sm font-medium text-gray-700 mb-2">
          Select Vendor
        </label>
        {!vendorsLoading && vendors.length === 0 ? (
          <p className="text-sm text-gray-500">No vendors linked to this group&apos;s products. Assign products with a vendor to this group to manage vendor group IDs.</p>
        ) : (
        <select
          value={selectedVendorId}
          onChange={(e) => {
            const newVendorId = e.target.value;
            console.log('🔍 Vendor dropdown changed:', {
              selectedValue: newVendorId,
              isValidGuid: isValidGuid(newVendorId),
              vendors: vendors.map(v => ({ Id: v.Id, VendorId: v.VendorId, Name: v.VendorName }))
            });
            if (!isValidGuid(newVendorId) && newVendorId !== '') {
              console.error('❌ Invalid vendor ID selected (not a GUID):', newVendorId);
              alert('Invalid vendor selection. Please select a vendor from the dropdown.');
              return;
            }
            setSelectedVendorId(newVendorId);
          }}
          className="w-full md:w-1/3 px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-oe-primary focus:border-oe-primary"
          disabled={vendorsLoading}
        >
          <option value="">-- Select a vendor --</option>
          {vendors.map((vendor) => {
            // Vendors API returns Id (not VendorId), so prioritize Id
            const vendorId = vendor.Id || vendor.VendorId || '';
            if (!vendorId) {
              console.warn('Vendor missing ID:', vendor);
              return null;
            }
            // Validate it's a GUID, not a name
            if (!isValidGuid(vendorId)) {
              console.warn('Vendor ID is not a GUID (skipping):', vendorId, 'Vendor:', vendor);
              return null;
            }
            return (
              <option key={vendorId} value={vendorId}>
                {vendor.VendorName}
              </option>
            );
          })}
        </select>
        )}
      </div>

      {selectedVendorId && (
        <>
          {/* Actions */}
          <div className="mb-4 flex items-center justify-between">
            <div>
              <h3 className="text-lg font-medium text-gray-900">
                Group IDs for {selectedVendor?.VendorName}
              </h3>
              <p className="text-sm text-gray-600 mt-1">
                {groupIds.length} Group ID{groupIds.length !== 1 ? 's' : ''} assigned
              </p>
            </div>
            <div className="flex items-center gap-2">
              {canEdit && (
                <button
                  onClick={handleGenerateClick}
                  disabled={generateLoading}
                  className="flex items-center px-4 py-2 border border-gray-300 text-gray-700 rounded-lg hover:bg-gray-50 disabled:opacity-50"
                >
                  {generateLoading ? <RefreshCw className="h-4 w-4 mr-2 animate-spin" /> : <Wand2 className="h-4 w-4 mr-2" />}
                  Generate group IDs
                </button>
              )}
              <button
                onClick={handleAdd}
                className="flex items-center px-4 py-2 text-white rounded-lg transition-colors"
                style={{ 
                  backgroundColor: 'var(--oe-primary)',
                }}
                onMouseEnter={(e) => e.currentTarget.style.backgroundColor = 'var(--oe-primary-dark)'}
                onMouseLeave={(e) => e.currentTarget.style.backgroundColor = 'var(--oe-primary)'}
              >
                <Plus className="h-4 w-4 mr-2" />
                Add Group ID
              </button>
            </div>
          </div>

          {/* Group IDs Table */}
          {loading ? (
            <div className="flex items-center justify-center py-12">
              <RefreshCw className="h-6 w-6 animate-spin text-gray-400" />
              <span className="ml-2 text-gray-600">Loading Group IDs...</span>
            </div>
          ) : groupIds.length === 0 ? (
            <div className="bg-gray-50 border border-gray-200 rounded-lg p-8 text-center">
              <Package className="h-12 w-12 text-gray-400 mx-auto mb-4" />
              <p className="text-gray-600 mb-2">No Group IDs found for this vendor</p>
              <p className="text-sm text-gray-500">
                Use &quot;Generate group IDs&quot; to create them from this group&apos;s products, or add them manually.
              </p>
            </div>
          ) : (
            <div className="bg-white border border border-gray-200 rounded-lg overflow-hidden">
              <table className="min-w-full divide-y divide-gray-200">
                <thead className="bg-gray-50">
                  <tr>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      Product
                    </th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      Group ID
                    </th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      Product Type
                    </th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      Type
                    </th>
                    <th className="px-6 py-3 text-right text-xs font-medium text-gray-500 uppercase tracking-wider">
                      Actions
                    </th>
                  </tr>
                </thead>
                <tbody className="bg-white divide-y divide-gray-200">
                  {groupIds.map((item, index) => (
                    <tr key={item.GroupProductId || `master-${item.VendorGroupId}-${index}`} className="hover:bg-gray-50">
                      <td className="px-6 py-4 whitespace-nowrap">
                        <div className="text-sm font-medium text-gray-900">
                          {item.ProductName || (item.ProductType === 'Master' ? 'Master (Group Level)' : 'N/A')}
                        </div>
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap">
                        <div className="flex items-center">
                          <Tag className="h-4 w-4 text-gray-400 mr-2" />
                          <span className="text-sm font-semibold text-gray-900">{item.VendorGroupId}</span>
                        </div>
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap">
                        <span className="text-sm text-gray-600">
                          {item.ProductType || 'N/A'}
                        </span>
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap">
                        {item.IsAutoGenerated ? (
                          <span className="inline-flex items-center px-2 py-1 rounded-full text-xs font-semibold bg-blue-100 text-blue-800">
                            <CheckCircle className="h-3 w-3 mr-1" />
                            Auto
                          </span>
                        ) : (
                          <span className="inline-flex items-center px-2 py-1 rounded-full text-xs font-semibold bg-gray-100 text-gray-800">
                            Manual
                          </span>
                        )}
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                        {canEdit ? (
                          <div className="flex items-center justify-end space-x-2">
                            <button
                              onClick={() => handleEdit(item)}
                              className="text-oe-primary hover:text-blue-900"
                              title="Edit Group ID"
                            >
                              <Edit className="h-4 w-4" />
                            </button>
                            <button
                              onClick={() => handleDelete(item)}
                              className="text-red-600 hover:text-red-900"
                              title="Delete Group ID"
                            >
                              <Trash2 className="h-4 w-4" />
                            </button>
                          </div>
                        ) : (
                          <span className="text-gray-400 text-xs">Read-only</span>
                        )}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
          {/* Location vendor group IDs section (canEdit-gated toggle, always shown when vendor selected) */}
          {selectedVendorId && canEdit && (
            <LocationVendorGroupIdsSection
              groupId={groupId}
              vendorId={selectedVendorId}
              vendorName={selectedVendor?.VendorName ?? ''}
              canEdit={canEdit}
            />
          )}
        </>
      )}

      {/* Generate group IDs modal */}
      {showGenerateModal && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50">
          <div className="bg-white rounded-lg max-w-2xl w-full max-h-[90vh] flex flex-col">
            <div className="p-6 border-b border-gray-200 flex items-center justify-between">
              <h3 className="text-lg font-semibold text-gray-900">Generate group IDs – Preview</h3>
              <button
                onClick={() => { setShowGenerateModal(false); setGeneratePreview([]); }}
                className="p-1 rounded hover:bg-gray-100 text-gray-500"
                aria-label="Close"
              >
                <X className="h-5 w-5" />
              </button>
            </div>
            <div className="p-6 overflow-auto flex-1">
              {generatePreview.length === 0 ? (
                <p className="text-gray-600">No products in this group need vendor group IDs, or no vendors with group ID settings are linked to this group&apos;s products.</p>
              ) : (
                <table className="min-w-full divide-y divide-gray-200">
                  <thead className="bg-gray-50">
                    <tr>
                      <th className="px-4 py-2 text-left text-xs font-medium text-gray-500 uppercase">Product</th>
                      <th className="px-4 py-2 text-left text-xs font-medium text-gray-500 uppercase">Product type</th>
                      <th className="px-4 py-2 text-left text-xs font-medium text-gray-500 uppercase">Group ID</th>
                      <th className="px-4 py-2 text-left text-xs font-medium text-gray-500 uppercase">Status</th>
                    </tr>
                  </thead>
                  <tbody className="bg-white divide-y divide-gray-200">
                    {generatePreview.map((row) => (
                      <tr key={row.groupProductId ?? `master-${row.vendorId}`}>
                        <td className="px-4 py-2 text-sm text-gray-900">{row.productName}</td>
                        <td className="px-4 py-2 text-sm text-gray-600">{row.productType}</td>
                        <td className="px-4 py-2 text-sm font-medium text-gray-900">{row.vendorGroupId}</td>
                        <td className="px-4 py-2 text-sm">
                          {row.sharesWithFallback ? (
                            <span className="text-gray-500">
                              Shared with {row.sharesWithProductName || 'linked product'}
                            </span>
                          ) : row.alreadyExists ? (
                            <span className="text-gray-500">Existing</span>
                          ) : (
                            <span className="text-green-600">To create</span>
                          )}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              )}
            </div>
            {generatePreview.length > 0 && generatePreview.every((p) => p.alreadyExists) && (
              <div className="px-6 py-3 bg-gray-50 border-t border-gray-200 text-sm text-gray-600">
                All products in this group already have vendor group IDs. Nothing to create.
              </div>
            )}
            <div className="p-6 border-t border-gray-200 flex justify-end gap-2">
              <button
                onClick={() => { setShowGenerateModal(false); setGeneratePreview([]); }}
                className="px-4 py-2 border border-gray-300 text-gray-700 rounded-lg hover:bg-gray-50"
              >
                Cancel
              </button>
              <button
                onClick={handleGenerateConfirmApply}
                disabled={generateApplying || generatePreview.length === 0 || generatePreview.every((p) => p.alreadyExists)}
                className="px-4 py-2 text-white rounded-lg disabled:opacity-50"
                style={{ backgroundColor: 'var(--oe-primary)' }}
                title={
                  generatePreview.length === 0
                    ? 'No products need vendor group IDs'
                    : generatePreview.every((p) => p.alreadyExists)
                      ? 'All already have group IDs'
                      : undefined
                }
              >
                {generateApplying ? 'Applying...' : 'Confirm & Apply'}
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Add Modal */}
      {showAddModal && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50">
          <div className="bg-white rounded-lg max-w-md w-full p-6">
            <h3 className="text-lg font-semibold text-gray-900 mb-4">Add Group ID</h3>
            
            <div className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  Product Type
                </label>
                <select
                  value={formData.productType}
                  onChange={(e) => handleProductTypeChange(e.target.value)}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-oe-primary"
                  required
                >
                  <option value="">-- Select type --</option>
                  <option value="Master">Master (Group Level)</option>
                  <option value="CoPay">CoPay</option>
                  <option value="HSA">HSA</option>
                </select>
                {formData.productType === 'Master' && (
                  <p className="mt-1 text-sm text-gray-500">
                    Master Group IDs are at the group level and don't require a specific product.
                  </p>
                )}
              </div>

              {!isMasterType && (
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">
                    Product <span className="text-red-500">*</span>
                  </label>
                  <select
                    value={formData.groupProductId}
                    onChange={(e) => setFormData({ ...formData, groupProductId: e.target.value })}
                    className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-oe-primary"
                    required={!isMasterType}
                  >
                    <option value="">-- Select product --</option>
                    {availableProducts.map((product) => (
                      <option key={product.GroupProductId} value={product.GroupProductId}>
                        {product.ProductName || product.Name}
                      </option>
                    ))}
                  </select>
                </div>
              )}

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  Group ID <span className="text-red-500">*</span>
                </label>
                <input
                  type="text"
                  value={formData.vendorGroupId}
                  onChange={(e) => setFormData({ ...formData, vendorGroupId: e.target.value })}
                  placeholder="e.g., 90285"
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-oe-primary"
                  required
                />
              </div>
            </div>

            <div className="mt-6 flex justify-end space-x-3">
              <button
                onClick={() => setShowAddModal(false)}
                className="px-4 py-2 border border-gray-300 text-gray-700 rounded-lg hover:bg-gray-50"
              >
                Cancel
              </button>
              <button
                onClick={handleSave}
                className="px-4 py-2 text-white rounded-lg transition-colors"
                style={{ 
                  backgroundColor: 'var(--oe-primary)',
                }}
                onMouseEnter={(e) => e.currentTarget.style.backgroundColor = 'var(--oe-primary-dark)'}
                onMouseLeave={(e) => e.currentTarget.style.backgroundColor = 'var(--oe-primary)'}
              >
                Add Group ID
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Edit Modal */}
      {showEditModal && editingGroupId && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50">
          <div className="bg-white rounded-lg max-w-md w-full p-6">
            <h3 className="text-lg font-semibold text-gray-900 mb-4">Edit Group ID</h3>
            
            <div className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  Product
                </label>
                <input
                  type="text"
                  value={editingGroupId.ProductName}
                  disabled
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg bg-gray-50 text-gray-600"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  Group ID
                </label>
                <input
                  type="text"
                  value={formData.vendorGroupId}
                  onChange={(e) => setFormData({ ...formData, vendorGroupId: e.target.value })}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-oe-primary"
                />
              </div>
            </div>

            <div className="mt-6 flex justify-end space-x-3">
              <button
                onClick={() => {
                  setShowEditModal(false);
                  setEditingGroupId(null);
                }}
                className="px-4 py-2 border border-gray-300 text-gray-700 rounded-lg hover:bg-gray-50"
              >
                Cancel
              </button>
              <button
                onClick={handleSave}
                className="px-4 py-2 text-white rounded-lg transition-colors"
                style={{ 
                  backgroundColor: 'var(--oe-primary)',
                }}
                onMouseEnter={(e) => e.currentTarget.style.backgroundColor = 'var(--oe-primary-dark)'}
                onMouseLeave={(e) => e.currentTarget.style.backgroundColor = 'var(--oe-primary)'}
              >
                Update Group ID
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default GroupVendorGroupIdsTab;
