// File: frontend/src/pages/tenant-admin/GroupLocationsTab.tsx
import {
  AlertCircle,
  Bug,
  Building,
  Building2,
  CheckCircle,
  CreditCard,
  Edit,
  Eye,
  Info,
  Lock,
  Mail,
  MapPin,
  Phone,
  Plus,
  Star,
  StarOff,
  Trash2,
  X
} from 'lucide-react';
import React, { useEffect, useState } from 'react';
import { US_STATES_FORMATTED } from '../../constants/form-options';
import { apiService } from '../../services/api.service';
import GroupLocationsService from '../../services/group-locations.service';
import { GroupsService } from '../../services/groups.service';
import {
  validateCreditCard,
  validateRoutingNumber as validateRouting
} from '../../utils/payment-validation';

// Types
interface VendorLocationIdEntry {
  VendorId: string;
  VendorLocationId: string;
  IsAutoGenerated: boolean;
}

interface GroupLocation {
  LocationId: string;
  GroupId: string;
  Name?: string;
  Address: string;
  Address2?: string;
  City: string;
  State: string;
  Zip: string;
  ContactName?: string;
  ContactPhone?: string;
  ContactEmail?: string;
  UseLocationACH: boolean;
  IsPrimary: boolean; // Added IsPrimary field
  Status: 'Active' | 'Inactive' | 'Archived';
  CreatedDate: string;
  ModifiedDate?: string;
  CreatedBy?: string;
  ModifiedBy?: string;
  /** Per-vendor location IDs for this location */
  VendorLocationIds?: VendorLocationIdEntry[];
  /** AllAboard platform location-level group ID override */
  AllAboardGroupId?: string | null;
  IsGroupIdOverride?: boolean;
}

interface PaymentMethod {
  PaymentMethodId: string;
  GroupId: string;
  LocationId?: string;
  Type: 'ACH' | 'CreditCard';
  Last4: string;
  BankName?: string;
  CardBrand?: string;
  ExpiryMonth?: number;
  ExpiryYear?: number;
  IsDefault: boolean;
  Status: 'Active' | 'Inactive';
  CreatedDate: string;
  BillingAddress?: string;
  BillingCity?: string;
  BillingState?: string;
  BillingZip?: string;
}

interface GroupLocationsTabProps {
  groupId: string;
  groupName: string;
}

// Custom Snackbar Component
interface SnackbarProps {
  open: boolean;
  message: string;
  severity: 'success' | 'error' | 'warning' | 'info';
  onClose: () => void;
}

const Snackbar: React.FC<SnackbarProps> = ({ open, message, severity, onClose }) => {
  useEffect(() => {
    if (open) {
      const timer = setTimeout(() => {
        onClose();
      }, 6000);
      return () => clearTimeout(timer);
    }
  }, [open, onClose]);

  if (!open) return null;

  const severityClasses = {
    success: 'bg-green-50 text-green-800 border-green-200',
    error: 'bg-red-50 text-red-800 border-red-200',
    warning: 'bg-amber-50 text-amber-800 border-amber-200',
    info: 'bg-blue-50 text-blue-800 border-blue-200'
  };

  return (
    <div className="fixed bottom-4 left-1/2 transform -translate-x-1/2 z-50">
      <div className={`flex items-center px-4 py-3 rounded-lg border ${severityClasses[severity]} shadow-lg`}>
        <span className="mr-2">{message}</span>
        <button onClick={onClose} className="ml-4">
          <X className="h-4 w-4" />
        </button>
      </div>
    </div>
  );
};

// Location Payment Method Modal Component
interface LocationPaymentMethodModalProps {
  open: boolean;
  onClose: () => void;
  onSave: () => void;
  groupId: string;
  locationId: string;
  showSnackbar: (message: string, severity: 'success' | 'error' | 'info' | 'warning') => void;
}

const LocationPaymentMethodModal: React.FC<LocationPaymentMethodModalProps> = ({
  open,
  onClose,
  onSave,
  groupId,
  locationId,
  showSnackbar,
}) => {
  const [paymentType, setPaymentType] = useState<'ACH' | 'CreditCard'>('ACH');
  const [saving, setSaving] = useState(false);
  const [loading, setLoading] = useState(true);
  const [showAccountNumber, setShowAccountNumber] = useState(false);
  const [showCardNumber, setShowCardNumber] = useState(true);
  const [isDevMode] = useState(window.location.hostname === 'localhost' || window.location.hostname === '127.0.0.1');
  const [hasDimeCustomerId, setHasDimeCustomerId] = useState(false);
  
  // Form fields
  const [formData, setFormData] = useState({
    billingAddress: '',
    billingCity: '',
    billingState: '',
    billingZip: '',
    phoneNumber: '',
    bankName: '',
    accountType: 'Checking',
    routingNumber: '',
    accountNumber: '',
    cardNumber: '',
    expiryMonth: '',
    expiryYear: '',
    cvv: '',
    cardholderName: ''
  });

  const [errors, setErrors] = useState<any>({});

  // Fetch location information for defaults
  useEffect(() => {
    if (open && locationId) {
      fetchLocationInfo();
    }
  }, [open, locationId]);

  const fetchLocationInfo = async () => {
    try {
      setLoading(true);
      const response = await apiService.get<{ success: boolean; data: GroupLocation }>(
        `/api/groups/${groupId}/locations/${locationId}`
      );
      
      if (response.success && response.data) {
        const location = response.data;
        
        // Check if location has DIME customer ID (we'll need to add this to location response)
        // For now, assume location uses group's customer or creates its own
        
        // Set default values from location
        setFormData(prev => ({
          ...prev,
          billingAddress: location.Address || '',
          billingCity: location.City || '',
          billingState: location.State || '',
          billingZip: location.Zip || '',
          phoneNumber: location.ContactPhone || '',
          cardholderName: location.ContactName || ''
        }));
      }
    } catch (error) {
      console.error('Error fetching location info:', error);
    } finally {
      setLoading(false);
    }
  };

  // Validation functions
  const validateRoutingNumber = (value: string): boolean => {
    const result = validateRouting(value);
    return result.isValid;
  };
  
  const getRoutingNumberError = (value: string): string | undefined => {
    if (!value) return 'Routing number is required';
    const result = validateRouting(value);
    return result.isValid ? undefined : (result.error || 'Invalid routing number');
  };

  const validateCardNumber = (value: string): boolean => {
    const result = validateCreditCard(value);
    return result.isValid;
  };

  const formatCardNumber = (value: string): string => {
    const cleanValue = value.replace(/\s/g, '');
    const groups = cleanValue.match(/.{1,4}/g);
    return groups ? groups.join(' ') : cleanValue;
  };

  const maskAccountNumber = (value: string): string => {
    if (!value || value.length <= 4) return value;
    return '*'.repeat(value.length - 4) + value.slice(-4);
  };

  const fillTestCardData = () => {
    const useACH = paymentType === 'ACH';
    
    if (useACH) {
      setFormData(prev => ({
        ...prev,
        bankName: 'Test Bank',
        accountType: 'Checking',
        routingNumber: '021000021',
        accountNumber: '1234567890',
        billingAddress: '123 Test Street',
        billingCity: 'Test City',
        billingState: 'CA',
        billingZip: '12345',
        phoneNumber: '7707892072'
      }));
      setPaymentType('ACH');
    } else {
      setFormData(prev => ({
        ...prev,
        cardNumber: '4111111111111111',
        expiryMonth: '12',
        expiryYear: String(new Date().getFullYear() + 2),
        cvv: '123',
        cardholderName: 'Test User',
        billingAddress: '123 Test Street',
        billingCity: 'Test City',
        billingState: 'CA',
        billingZip: '12345',
        phoneNumber: '7707892072'
      }));
      setPaymentType('CreditCard');
    }
    
    setErrors({});
  };

  const handleInputChange = (field: string, value: string) => {
    setFormData(prev => ({ ...prev, [field]: value }));
    
    // Validate routing number in real-time when user types
    if (field === 'routingNumber' && value.length === 9) {
      const routingValidation = validateRouting(value);
      if (routingValidation.isValid) {
        setErrors((prev: any) => ({ ...prev, [field]: undefined }));
      } else {
        setErrors((prev: any) => ({ ...prev, [field]: routingValidation.error || 'Invalid routing number' }));
      }
      return;
    }
    
    // Clear error for this field when user starts typing
    if (errors[field]) {
      if (field === 'cardNumber') {
        const cleanValue = value.replace(/\D/g, '');
        if (cleanValue.length >= 13 && cleanValue.length <= 21 && /^\d+$/.test(cleanValue)) {
          setErrors((prev: any) => ({ ...prev, [field]: undefined }));
        }
      } else if (field === 'routingNumber' && value.length < 9) {
        // Clear error if routing number is incomplete
        setErrors((prev: any) => ({ ...prev, [field]: undefined }));
      } else {
        setErrors((prev: any) => ({ ...prev, [field]: undefined }));
      }
    }
  };

  const validateForm = (): boolean => {
    const newErrors: any = {};

    if (!formData.billingAddress) newErrors.billingAddress = 'Billing address is required';
    if (!formData.billingCity) newErrors.billingCity = 'City is required';
    if (!formData.billingState) newErrors.billingState = 'State is required';
    if (!formData.billingZip) newErrors.billingZip = 'ZIP code is required';
    
    if (!hasDimeCustomerId) {
      if (!formData.phoneNumber) {
        newErrors.phoneNumber = 'Phone number is required for payment processing';
      } else {
        const phoneDigits = formData.phoneNumber.replace(/\D/g, '');
        if (phoneDigits.length < 10) {
          newErrors.phoneNumber = 'Phone number must be at least 10 digits';
        }
      }
    }

    if (paymentType === 'ACH') {
      if (!formData.bankName) newErrors.bankName = 'Bank name is required';
      if (!formData.routingNumber) {
        newErrors.routingNumber = 'Routing number is required';
      } else {
        const routingValidation = validateRouting(formData.routingNumber);
        if (!routingValidation.isValid) {
          newErrors.routingNumber = routingValidation.error || 'Invalid routing number';
        }
      }
      if (!formData.accountNumber) newErrors.accountNumber = 'Account number is required';
    } else {
      if (!formData.cardNumber) newErrors.cardNumber = 'Card number is required';
      else {
        const cleanNumber = formData.cardNumber.replace(/\s/g, '');
        if (cleanNumber.length < 13) {
          newErrors.cardNumber = 'Card number must be at least 13 digits';
        } else if (cleanNumber.length > 21) {
          newErrors.cardNumber = 'Card number cannot exceed 21 digits';
        } else if (!/^\d+$/.test(cleanNumber)) {
          newErrors.cardNumber = 'Card number must contain only numbers';
        } else if (!validateCardNumber(formData.cardNumber)) {
          newErrors.cardNumber = 'Invalid card number (failed checksum validation)';
        }
      }
      if (!formData.expiryMonth) newErrors.expiryMonth = 'Expiry month is required';
      if (!formData.expiryYear) newErrors.expiryYear = 'Expiry year is required';
      if (!formData.cvv) newErrors.cvv = 'CVV is required';
      else if (!/^\d{3,4}$/.test(formData.cvv)) {
        newErrors.cvv = 'CVV must be 3 or 4 digits';
      }
      if (!formData.cardholderName) newErrors.cardholderName = 'Cardholder name is required';

      const currentDate = new Date();
      const currentYear = currentDate.getFullYear();
      const currentMonth = currentDate.getMonth() + 1;
      const expiryYear = parseInt(formData.expiryYear);
      const expiryMonth = parseInt(formData.expiryMonth);
      
      if (expiryYear < currentYear || (expiryYear === currentYear && expiryMonth < currentMonth)) {
        newErrors.expiryMonth = 'Card has expired';
      }
    }

    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const isFormValid = (): boolean => {
    if (!formData.billingAddress || !formData.billingCity || !formData.billingState || !formData.billingZip) {
      return false;
    }
    
    if (!hasDimeCustomerId) {
      if (!formData.phoneNumber) return false;
      const phoneDigits = formData.phoneNumber.replace(/\D/g, '');
      if (phoneDigits.length < 10) return false;
    }
    
    if (paymentType === 'ACH') {
      return !!(formData.bankName && formData.routingNumber && formData.accountNumber && 
                validateRoutingNumber(formData.routingNumber));
    } else {
      const cleanNumber = formData.cardNumber.replace(/\s/g, '');
      return !!(formData.cardNumber && formData.cardholderName && formData.expiryMonth && formData.expiryYear && formData.cvv &&
                cleanNumber.length >= 13 && validateCardNumber(cleanNumber) && /^\d{3,4}$/.test(formData.cvv));
    }
  };

  const handleSave = async () => {
    if (!validateForm()) return;

    setSaving(true);
    try {
      const payload = {
        type: paymentType,
        billingAddress: formData.billingAddress,
        billingCity: formData.billingCity,
        billingState: formData.billingState,
        billingZip: formData.billingZip,
        ...(paymentType === 'ACH' 
          ? {
              bankName: formData.bankName,
              accountType: formData.accountType,
              routingNumber: formData.routingNumber,
              accountNumber: formData.accountNumber
            }
          : {
              cardNumber: formData.cardNumber.replace(/\s/g, ''),
              expiryMonth: parseInt(formData.expiryMonth),
              expiryYear: parseInt(formData.expiryYear),
              cvv: formData.cvv,
              cardholderName: formData.cardholderName
            })
      };

      if (!hasDimeCustomerId && formData.phoneNumber) {
        (payload as any).phoneNumber = formData.phoneNumber;
      }

      const response = await apiService.post<{ success: boolean; message?: string; data: PaymentMethod }>(
        `/api/groups/${groupId}/locations/${locationId}/payment-method`,
        payload
      );

      if (response.success) {
        showSnackbar('Payment method added successfully', 'success');
        onSave();
        setTimeout(() => onClose(), 1000);
      } else {
        const errorMessage = response.message || 'Failed to add payment method';
        showSnackbar(errorMessage, 'error');
      }
    } catch (error: any) {
      console.error('Error adding payment method:', error);
      showSnackbar(error?.message || 'Failed to add payment method', 'error');
    } finally {
      setSaving(false);
    }
  };

  const states = US_STATES_FORMATTED;

  const currentYear = new Date().getFullYear();
  const years = Array.from({ length: 20 }, (_, i) => currentYear + i);
  const months = Array.from({ length: 12 }, (_, i) => ({
    value: String(i + 1).padStart(2, '0'),
    label: String(i + 1).padStart(2, '0')
  }));

  if (!open) return null;

  return (
    <div className="fixed inset-0 z-50 overflow-y-auto">
      <div className="flex items-center justify-center min-h-screen pt-4 px-4 pb-20 text-center sm:block sm:p-0">
        <div className="fixed inset-0 bg-gray-500 bg-opacity-75 transition-opacity" onClick={onClose}></div>

        <div className="inline-block align-bottom bg-white rounded-lg text-left overflow-hidden shadow-xl transform transition-all sm:my-8 sm:align-middle sm:max-w-2xl sm:w-full">
          <div className="bg-white px-4 pt-5 pb-4 sm:p-6 sm:pb-4">
            <div className="flex items-center justify-between mb-4">
              <h3 className="text-xl font-semibold text-gray-900">Add Payment Method</h3>
              <div className="flex items-center space-x-2">
                {isDevMode && (
                  <button
                    onClick={fillTestCardData}
                    className="px-3 py-1 text-xs bg-blue-100 text-oe-primary-dark rounded-md hover:bg-blue-200 transition-colors inline-flex items-center"
                  >
                    <Bug className="h-3 w-3 mr-1" />
                    Fill test data (DEV)
                  </button>
                )}
                <Lock className="h-5 w-5 text-gray-400" />
              </div>
            </div>

            {loading ? (
              <div className="flex justify-center py-8">
                <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-oe-primary"></div>
              </div>
            ) : (
              <>
                <div className="bg-blue-50 border border-blue-200 rounded-lg p-4 mb-4">
                  <div className="flex">
                    <Info className="h-5 w-5 text-oe-primary mt-0.5 mr-2 flex-shrink-0" />
                    <p className="text-sm text-blue-800">
                      Your payment information is encrypted and secure. Payment processing will be configured at the tenant level in your admin settings.
                    </p>
                  </div>
                </div>

                <div className="mb-4">
                  <label className="block text-sm font-medium text-gray-700 mb-2">Payment Type</label>
                  <select
                    value={paymentType}
                    onChange={(e) => setPaymentType(e.target.value as 'ACH' | 'CreditCard')}
                    className="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-oe-primary focus:border-oe-primary"
                  >
                    <option value="ACH">Bank Account (ACH)</option>
                    <option value="CreditCard">Credit Card</option>
                  </select>
                </div>

                {paymentType === 'ACH' ? (
                  <>
                    <h4 className="text-sm font-medium text-gray-700 mt-4 mb-2">Bank Account Information</h4>
                    <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                      <div className="col-span-2">
                        <label className="block text-sm font-medium text-gray-700 mb-1">
                          Bank Name <span className="text-red-500">*</span>
                        </label>
                        <input
                          type="text"
                          value={formData.bankName}
                          onChange={(e) => handleInputChange('bankName', e.target.value)}
                          className={`w-full px-3 py-2 border ${errors.bankName ? 'border-red-500' : 'border-gray-300'} rounded-md focus:ring-oe-primary focus:border-oe-primary`}
                        />
                        {errors.bankName && <p className="text-red-500 text-xs mt-1">{errors.bankName}</p>}
                      </div>

                      <div>
                        <label className="block text-sm font-medium text-gray-700 mb-1">Account Type</label>
                        <select
                          value={formData.accountType}
                          onChange={(e) => handleInputChange('accountType', e.target.value)}
                          className="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-oe-primary focus:border-oe-primary"
                        >
                          <option value="Checking">Checking</option>
                          <option value="Savings">Savings</option>
                        </select>
                      </div>

                      <div>
                        <label className="block text-sm font-medium text-gray-700 mb-1">
                          Routing Number <span className="text-red-500">*</span>
                        </label>
                        <input
                          type="text"
                          value={formData.routingNumber}
                          onChange={(e) => {
                            const value = e.target.value.replace(/\D/g, '').slice(0, 9);
                            handleInputChange('routingNumber', value);
                          }}
                          placeholder="9 digits"
                          maxLength={9}
                          className={`w-full px-3 py-2 border ${errors.routingNumber ? 'border-red-500' : 'border-gray-300'} rounded-md focus:ring-oe-primary focus:border-oe-primary`}
                        />
                        {errors.routingNumber && <p className="text-red-500 text-xs mt-1">{errors.routingNumber}</p>}
                      </div>

                      <div className="col-span-2">
                        <label className="block text-sm font-medium text-gray-700 mb-1">
                          Account Number <span className="text-red-500">*</span>
                        </label>
                        <div className="relative">
                          <input
                            type={showAccountNumber ? 'text' : 'password'}
                            value={formData.accountNumber}
                            onChange={(e) => handleInputChange('accountNumber', e.target.value)}
                            className={`w-full px-3 py-2 pr-10 border ${errors.accountNumber ? 'border-red-500' : 'border-gray-300'} rounded-md focus:ring-oe-primary focus:border-oe-primary`}
                          />
                          <button
                            type="button"
                            onClick={() => setShowAccountNumber(!showAccountNumber)}
                            className="absolute inset-y-0 right-0 pr-3 flex items-center"
                          >
                            <Eye className={`h-4 w-4 ${showAccountNumber ? 'text-oe-primary' : 'text-gray-400'}`} />
                          </button>
                        </div>
                        {errors.accountNumber && <p className="text-red-500 text-xs mt-1">{errors.accountNumber}</p>}
                      </div>
                    </div>
                  </>
                ) : (
                  <>
                    <h4 className="text-sm font-medium text-gray-700 mt-4 mb-2">Card Information</h4>
                    <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
                      <div className="col-span-3">
                        <label className="block text-sm font-medium text-gray-700 mb-1">
                          Cardholder Name <span className="text-red-500">*</span>
                        </label>
                        <input
                          type="text"
                          value={formData.cardholderName}
                          onChange={(e) => handleInputChange('cardholderName', e.target.value)}
                          className={`w-full px-3 py-2 border ${errors.cardholderName ? 'border-red-500' : 'border-gray-300'} rounded-md focus:ring-oe-primary focus:border-oe-primary`}
                        />
                        {errors.cardholderName && <p className="text-red-500 text-xs mt-1">{errors.cardholderName}</p>}
                      </div>

                      <div className="col-span-3">
                        <label className="block text-sm font-medium text-gray-700 mb-1">
                          Card Number <span className="text-red-500">*</span>
                        </label>
                        <div className="relative">
                          <input
                            type={showCardNumber ? 'text' : 'password'}
                            value={showCardNumber ? formatCardNumber(formData.cardNumber) : maskAccountNumber(formData.cardNumber)}
                            onChange={(e) => {
                              const value = e.target.value.replace(/\D/g, '').slice(0, 21);
                              handleInputChange('cardNumber', value);
                            }}
                            placeholder="1234 5678 9012 3456"
                            className={`w-full px-3 py-2 pr-10 border ${errors.cardNumber ? 'border-red-500' : 'border-gray-300'} rounded-md focus:ring-oe-primary focus:border-oe-primary`}
                          />
                          <button
                            type="button"
                            onClick={() => setShowCardNumber(!showCardNumber)}
                            className="absolute inset-y-0 right-0 pr-3 flex items-center"
                          >
                            <Eye className={`h-4 w-4 ${showCardNumber ? 'text-oe-primary' : 'text-gray-400'}`} />
                          </button>
                        </div>
                        {errors.cardNumber ? (
                          <p className="text-red-500 text-xs mt-1">{errors.cardNumber}</p>
                        ) : (
                          <div className="text-gray-500 text-xs mt-1">
                            <p>Enter 13-21 digits (Visa: 13-19, Mastercard: 16, Amex: 15, Discover: 16)</p>
                          </div>
                        )}
                      </div>

                      <div>
                        <label className="block text-sm font-medium text-gray-700 mb-1">
                          Month <span className="text-red-500">*</span>
                        </label>
                        <select
                          value={formData.expiryMonth}
                          onChange={(e) => handleInputChange('expiryMonth', e.target.value)}
                          className={`w-full px-3 py-2 border ${errors.expiryMonth ? 'border-red-500' : 'border-gray-300'} rounded-md focus:ring-oe-primary focus:border-oe-primary`}
                        >
                          <option value="">Select</option>
                          {months.map(month => (
                            <option key={month.value} value={month.value}>{month.label}</option>
                          ))}
                        </select>
                        {errors.expiryMonth && <p className="text-red-500 text-xs mt-1">{errors.expiryMonth}</p>}
                      </div>

                      <div>
                        <label className="block text-sm font-medium text-gray-700 mb-1">
                          Year <span className="text-red-500">*</span>
                        </label>
                        <select
                          value={formData.expiryYear}
                          onChange={(e) => handleInputChange('expiryYear', e.target.value)}
                          className={`w-full px-3 py-2 border ${errors.expiryYear ? 'border-red-500' : 'border-gray-300'} rounded-md focus:ring-oe-primary focus:border-oe-primary`}
                        >
                          <option value="">Select</option>
                          {years.map(year => (
                            <option key={year} value={year}>{year}</option>
                          ))}
                        </select>
                        {errors.expiryYear && <p className="text-red-500 text-xs mt-1">{errors.expiryYear}</p>}
                      </div>

                      <div>
                        <label className="block text-sm font-medium text-gray-700 mb-1">
                          CVV <span className="text-red-500">*</span>
                        </label>
                        <input
                          type="password"
                          value={formData.cvv}
                          onChange={(e) => {
                            const value = e.target.value.replace(/\D/g, '').slice(0, 4);
                            handleInputChange('cvv', value);
                          }}
                          placeholder="3-4 digits"
                          maxLength={4}
                          className={`w-full px-3 py-2 border ${errors.cvv ? 'border-red-500' : 'border-gray-300'} rounded-md focus:ring-oe-primary focus:border-oe-primary`}
                        />
                        {errors.cvv && <p className="text-red-500 text-xs mt-1">{errors.cvv}</p>}
                      </div>
                    </div>
                  </>
                )}

                <div className="border-t border-gray-200 my-6"></div>

                <h4 className="text-sm font-medium text-gray-700 mb-2">Billing Address</h4>
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                  <div className="col-span-2">
                    <label className="block text-sm font-medium text-gray-700 mb-1">
                      Street Address <span className="text-red-500">*</span>
                    </label>
                    <input
                      type="text"
                      value={formData.billingAddress}
                      onChange={(e) => handleInputChange('billingAddress', e.target.value)}
                      className={`w-full px-3 py-2 border ${errors.billingAddress ? 'border-red-500' : 'border-gray-300'} rounded-md focus:ring-oe-primary focus:border-oe-primary`}
                    />
                    {errors.billingAddress && <p className="text-red-500 text-xs mt-1">{errors.billingAddress}</p>}
                  </div>

                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">
                      City <span className="text-red-500">*</span>
                    </label>
                    <input
                      type="text"
                      value={formData.billingCity}
                      onChange={(e) => handleInputChange('billingCity', e.target.value)}
                      className={`w-full px-3 py-2 border ${errors.billingCity ? 'border-red-500' : 'border-gray-300'} rounded-md focus:ring-oe-primary focus:border-oe-primary`}
                    />
                    {errors.billingCity && <p className="text-red-500 text-xs mt-1">{errors.billingCity}</p>}
                  </div>

                  <div className="flex gap-4">
                    <div className="flex-1">
                      <label className="block text-sm font-medium text-gray-700 mb-1">
                        State <span className="text-red-500">*</span>
                      </label>
                      <select
                        value={formData.billingState}
                        onChange={(e) => handleInputChange('billingState', e.target.value)}
                        className={`w-full px-3 py-2 border ${errors.billingState ? 'border-red-500' : 'border-gray-300'} rounded-md focus:ring-oe-primary focus:border-oe-primary`}
                      >
                        <option value="">Select</option>
                        {states.map(state => (
                          <option key={state.value} value={state.value}>{state.label}</option>
                        ))}
                      </select>
                      {errors.billingState && <p className="text-red-500 text-xs mt-1">{errors.billingState}</p>}
                    </div>

                    <div className="flex-1">
                      <label className="block text-sm font-medium text-gray-700 mb-1">
                        ZIP Code <span className="text-red-500">*</span>
                      </label>
                      <input
                        type="text"
                        value={formData.billingZip}
                        onChange={(e) => {
                          const value = e.target.value.replace(/\D/g, '').slice(0, 10);
                          handleInputChange('billingZip', value);
                        }}
                        className={`w-full px-3 py-2 border ${errors.billingZip ? 'border-red-500' : 'border-gray-300'} rounded-md focus:ring-oe-primary focus:border-oe-primary`}
                      />
                      {errors.billingZip && <p className="text-red-500 text-xs mt-1">{errors.billingZip}</p>}
                    </div>
                  </div>
                </div>

                {!hasDimeCustomerId && (
                  <div className="mt-6">
                    <label className="block text-sm font-medium text-gray-700 mb-1">
                      Phone Number <span className="text-red-500">*</span>
                    </label>
                    <input
                      type="tel"
                      value={formData.phoneNumber}
                      onChange={(e) => handleInputChange('phoneNumber', e.target.value)}
                      placeholder="(555) 123-4567"
                      className={`w-full px-3 py-2 border ${errors.phoneNumber ? 'border-red-500' : 'border-gray-300'} rounded-md focus:ring-oe-primary focus:border-oe-primary`}
                    />
                    {errors.phoneNumber && <p className="text-red-500 text-xs mt-1">{errors.phoneNumber}</p>}
                    <p className="text-xs text-gray-500 mt-1">Required for payment processing setup</p>
                  </div>
                )}
              </>
            )}
          </div>

          <div className="bg-gray-50 px-4 py-3 sm:px-6 sm:flex sm:flex-row-reverse">
            <button
              type="button"
              onClick={handleSave}
              disabled={saving || loading || !isFormValid()}
              className="w-full inline-flex justify-center rounded-md border border-transparent shadow-sm px-4 py-2 bg-oe-primary text-base font-medium text-white hover:bg-oe-dark focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-oe-primary sm:ml-3 sm:w-auto sm:text-sm disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {saving ? (
                <>
                  <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white mr-2"></div>
                  Processing...
                </>
              ) : (
                'Add Payment Method'
              )}
            </button>
            <button
              type="button"
              onClick={onClose}
              className="mt-3 w-full inline-flex justify-center rounded-md border border-gray-300 shadow-sm px-4 py-2 bg-white text-base font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-oe-primary sm:mt-0 sm:ml-3 sm:w-auto sm:text-sm"
            >
              Cancel
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

// Location Form Modal Component
interface LocationModalProps {
  open: boolean;
  onClose: () => void;
  location?: GroupLocation | null;
  onSave: () => void;
  groupId: string;
  showSnackbar: (message: string, severity: 'success' | 'error' | 'info' | 'warning') => void;
}

const LocationModal: React.FC<LocationModalProps> = ({
  open,
  onClose,
  location,
  onSave,
  groupId,
  showSnackbar
}) => {
  const [saving, setSaving] = useState(false);
  const [activeTab, setActiveTab] = useState<'location' | 'contact' | 'payment'>('location');
  const [formData, setFormData] = useState({
    name: '',
    address: '',
    address2: '',
    city: '',
    state: '',
    zip: '',
    contactName: '',
    contactPhone: '',
    contactEmail: '',
    useLocationACH: false,
    allAboardGroupId: '',
    overrideAllAboardGroupId: false,
  });
  const [errors, setErrors] = useState<any>({});
  const [allAboardGroupIdValidation, setAllAboardGroupIdValidation] = useState<{
    available?: boolean;
    message?: string;
    checking?: boolean;
  }>({});
  const [paymentMethods, setPaymentMethods] = useState<PaymentMethod[]>([]);
  const [loadingPaymentMethods, setLoadingPaymentMethods] = useState(false);
  const [paymentMethodModalOpen, setPaymentMethodModalOpen] = useState(false);
  const [deletePaymentMethodConfirm, setDeletePaymentMethodConfirm] = useState<string | null>(null);
  const [setDefaultPaymentMethodConfirm, setSetDefaultPaymentMethodConfirm] = useState<string | null>(null);

  useEffect(() => {
    if (open) {
      if (location) {
        // Edit mode - populate form
        setFormData({
          name: location.Name || '',
          address: location.Address || '',
          address2: location.Address2 || '',
          city: location.City || '',
          state: location.State || '',
          zip: location.Zip || '',
          contactName: location.ContactName || '',
          contactPhone: location.ContactPhone || '',
          contactEmail: location.ContactEmail || '',
          useLocationACH: location.UseLocationACH || false,
          allAboardGroupId: location.AllAboardGroupId || '',
          overrideAllAboardGroupId: !!location.IsGroupIdOverride,
        });
        // Load payment methods for this location
        loadPaymentMethods(location.LocationId);
        // Set active tab based on whether location has ACH enabled
        setActiveTab(location.UseLocationACH ? 'location' : 'location');
      } else {
        // Create mode - reset form
        setFormData({
          name: '',
          address: '',
          address2: '',
          city: '',
          state: '',
          zip: '',
          contactName: '',
          contactPhone: '',
          contactEmail: '',
          useLocationACH: false,
          allAboardGroupId: '',
          overrideAllAboardGroupId: false,
        });
        setPaymentMethods([]);
        setActiveTab('location');
      }
      setErrors({});
      setAllAboardGroupIdValidation({});
    }
  }, [open, location]);

  const loadPaymentMethods = async (locationId: string) => {
    try {
      setLoadingPaymentMethods(true);
      const response = await apiService.get<{ success: boolean; data: PaymentMethod[] }>(
        `/api/groups/${groupId}/locations/${locationId}/payment-methods`
      );

      if (response.success && response.data) {
        setPaymentMethods(response.data);
      }
    } catch (error) {
      console.error('Error loading payment methods:', error);
    } finally {
      setLoadingPaymentMethods(false);
    }
  };

  const handleDeletePaymentMethod = async (paymentMethodId: string) => {
    if (!location) return;
    
    try {
      const response = await apiService.delete<{ success: boolean; message?: string; error?: { code?: string } }>(
        `/api/groups/${groupId}/locations/${location.LocationId}/payment-methods/${paymentMethodId}`
      );

      if (response.success) {
        showSnackbar('Payment method deleted successfully', 'success');
        loadPaymentMethods(location.LocationId);
      } else {
        showSnackbar(response.message || 'Failed to delete payment method', 'error');
      }
    } catch (error: any) {
      console.error('Error deleting payment method:', error);
      const errorMessage = error?.response?.data?.message || 
        error?.message || 
        'Failed to delete payment method';
      
      // Show specific error message for last payment method deletion
      if (error?.response?.data?.error?.code === 'LAST_PAYMENT_METHOD_DELETION_NOT_ALLOWED') {
        showSnackbar(
          'Cannot delete the last payment method. Locations with separate payment accounts must have at least one active payment method. To disable separate payments, uncheck "This location pays for its own members" in the Location tab.',
          'error'
        );
      } else {
        showSnackbar(errorMessage, 'error');
      }
    } finally {
      setDeletePaymentMethodConfirm(null);
    }
  };

  const handleSetDefaultPaymentMethod = async (paymentMethodId: string) => {
    if (!location) return;
    
    try {
      const response = await apiService.put<{ success: boolean; message?: string }>(
        `/api/groups/${groupId}/locations/${location.LocationId}/payment-methods/${paymentMethodId}/set-default`
      );

      if (response.success) {
        showSnackbar('Default payment method updated successfully', 'success');
        loadPaymentMethods(location.LocationId);
      } else {
        showSnackbar('Failed to update default payment method', 'error');
      }
    } catch (error: any) {
      console.error('Error setting default payment method:', error);
      showSnackbar(error?.message || 'Failed to update default payment method', 'error');
    }
    setSetDefaultPaymentMethodConfirm(null);
  };

  const getPaymentMethodDisplay = (method: PaymentMethod) => {
    if (method.Type === 'ACH') {
      return `${method.BankName || 'Bank Account'} ••••${method.Last4}`;
    } else {
      return `${method.CardBrand || 'Credit Card'} ••••${method.Last4}`;
    }
  };

  const formatDate = (dateString: string, format: string = 'MMM yyyy'): string => {
    const date = new Date(dateString);
    const months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
    
    if (format === 'MMM yyyy') {
      return `${months[date.getMonth()]} ${date.getFullYear()}`;
    }
    
    return `${months[date.getMonth()]} ${date.getDate()}, ${date.getFullYear()}`;
  };

  const handleInputChange = (field: string, value: string | boolean) => {
    setFormData(prev => ({ ...prev, [field]: value }));
    if (errors[field]) {
      setErrors((prev: any) => ({ ...prev, [field]: undefined }));
    }
  };

  const validateForm = (): boolean => {
    const newErrors: any = {};

    if (!formData.address.trim()) newErrors.address = 'Address is required';
    if (!formData.city.trim()) newErrors.city = 'City is required';
    if (!formData.state) newErrors.state = 'State is required';
    if (!formData.zip.trim()) newErrors.zip = 'ZIP code is required';

    // Contact Name validation - REQUIRED for invoice delivery
    if (!formData.contactName || !formData.contactName.trim()) {
      newErrors.contactName = 'Contact name is required for invoice delivery';
    }

    // Email validation - REQUIRED for invoice delivery
    if (!formData.contactEmail || !formData.contactEmail.trim()) {
      newErrors.contactEmail = 'Contact email is required for invoice delivery';
    } else if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(formData.contactEmail)) {
      newErrors.contactEmail = 'Please enter a valid email address';
    }

    // Validate payment methods if UseLocationACH is checked
    if (formData.useLocationACH && location) {
      const activePaymentMethods = paymentMethods.filter(m => m.Status === 'Active');
      if (activePaymentMethods.length === 0) {
        newErrors.paymentMethods = 'At least one active payment method is required when location pays for its own members';
      }
    }

    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    
    // Validate payment methods if UseLocationACH is checked
    if (formData.useLocationACH && location) {
      const activePaymentMethods = paymentMethods.filter(m => m.Status === 'Active');
      if (activePaymentMethods.length === 0) {
        showSnackbar('At least one active payment method is required when location pays for its own members. Please add a payment method in the Payment Methods tab.', 'error');
        setActiveTab('payment');
        return;
      }
    }
    
    if (!validateForm()) {
      // Switch to the tab with errors
      if (errors.address || errors.city || errors.state || errors.zip) {
        setActiveTab('location');
      } else if (errors.contactName || errors.contactEmail) {
        setActiveTab('contact');
      }
      return;
    }

    setSaving(true);
    try {
      const url = location 
        ? `/api/groups/${groupId}/locations/${location.LocationId}`
        : `/api/groups/${groupId}/locations`;
      
      const method = location ? 'PUT' : 'POST';
      
      const payload = {
        ...formData,
        allAboardGroupId: formData.overrideAllAboardGroupId
          ? (formData.allAboardGroupId || null)
          : null,
      };
      const response = method === 'POST' 
        ? await apiService.post<{ success: boolean; message?: string; data: GroupLocation }>(url, payload)
        : await apiService.put<{ success: boolean; message?: string; data: GroupLocation }>(url, payload);

      if (response.success) {
        if (location) {
          const overrideValue = formData.overrideAllAboardGroupId
            ? ((formData.allAboardGroupId as string).trim() || null)
            : null;
          const groupIdRes = await GroupsService.updateLocationGroupId(
            groupId,
            location.LocationId,
            overrideValue
          );
          if (!groupIdRes.success) {
            throw new Error(groupIdRes.message || 'Location saved but group ID update failed');
          }
        }
        showSnackbar(
          location ? 'Location updated successfully' : 'Location created successfully',
          'success'
        );
        onSave();
        onClose();
      } else {
        throw new Error(response.message || 'Failed to save location');
      }
    } catch (error: any) {
      console.error('Error saving location:', error);
      
      // Handle payment method validation error
      if (error?.response?.data?.error?.code === 'PAYMENT_METHOD_REQUIRED') {
        setErrors({ paymentMethods: error.response.data.message });
        showSnackbar(error.response.data.message, 'error');
        setActiveTab('payment');
        setSaving(false);
        return;
      }
      
      showSnackbar(
        error?.response?.data?.message || error?.message || 'Failed to save location. Please try again.',
        'error'
      );
    } finally {
      setSaving(false);
    }
  };

  if (!open) return null;

  return (
    <div 
      className="fixed bg-black bg-opacity-50 flex items-center justify-center z-[9999]" 
      style={{ 
        position: 'fixed', 
        top: 0, 
        left: 0, 
        right: 0, 
        bottom: 0, 
        width: '100vw', 
        height: '100vh',
        margin: 0,
        padding: '1rem'
      }}
      onClick={(e) => {
        if (e.target === e.currentTarget) {
          onClose();
        }
      }}
    >
      <div className="bg-white rounded-lg max-w-2xl w-full p-6 shadow-xl max-h-[90vh] overflow-y-auto" onClick={(e) => e.stopPropagation()}>
        <div className="flex items-center justify-between mb-6">
          <h3 className="text-xl font-semibold text-oe-neutral-dark">
            {location ? 'Edit Location' : 'Add New Location'}
          </h3>
          <button
            onClick={onClose}
            className="text-gray-400 hover:text-gray-600 transition-colors"
          >
            <X className="h-5 w-5" />
          </button>
        </div>

        {/* Error Summary (if any) */}
        {Object.keys(errors).length > 0 && (
          <div className="mb-4 bg-red-50 border border-red-200 rounded-lg p-4">
            <div className="flex">
              <AlertCircle className="h-5 w-5 text-red-600 mt-0.5 flex-shrink-0" />
              <div className="ml-3">
                <h4 className="text-sm font-medium text-red-800">Please fix the following errors:</h4>
                <ul className="mt-2 text-sm text-red-700 list-disc list-inside space-y-1">
                  {Object.entries(errors).map(([field, message]) => (
                    <li key={field}>{message as string}</li>
                  ))}
                </ul>
              </div>
            </div>
          </div>
        )}

        {/* Tabs */}
        <div className="border-b border-gray-200 mb-4">
          <nav className="flex space-x-8" aria-label="Tabs">
            <button
              type="button"
              onClick={() => setActiveTab('location')}
              className={`py-4 px-1 border-b-2 font-medium text-sm relative ${
                activeTab === 'location'
                  ? 'border-oe-primary text-oe-primary'
                  : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300'
              }`}
            >
              Location <span className="text-red-500">*</span>
              {(errors.address || errors.city || errors.state || errors.zip) && (
                <span className="absolute -top-1 -right-1 h-2 w-2 bg-red-500 rounded-full"></span>
              )}
            </button>
            <button
              type="button"
              onClick={() => setActiveTab('contact')}
              className={`py-4 px-1 border-b-2 font-medium text-sm relative ${
                activeTab === 'contact'
                  ? 'border-oe-primary text-oe-primary'
                  : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300'
              }`}
            >
              Contact <span className="text-red-500">*</span>
              {(errors.contactName || errors.contactEmail) && (
                <span className="absolute -top-1 -right-1 h-2 w-2 bg-red-500 rounded-full"></span>
              )}
            </button>
            {location && (
              <button
                type="button"
                onClick={() => setActiveTab('payment')}
                className={`py-4 px-1 border-b-2 font-medium text-sm relative ${
                  activeTab === 'payment'
                    ? 'border-oe-primary text-oe-primary'
                    : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300'
                }`}
              >
                Payment Methods
                {errors.paymentMethods && (
                  <span className="absolute -top-1 -right-1 h-2 w-2 bg-red-500 rounded-full"></span>
                )}
              </button>
            )}
          </nav>
        </div>

        <form onSubmit={handleSubmit} className="space-y-4">
          {/* Location Tab */}
          {activeTab === 'location' && (
            <div className="space-y-4">
              {/* Location Name (Optional) */}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  Location Name <span className="text-gray-400">(Optional)</span>
                </label>
                <input
                  type="text"
                  value={formData.name}
                  onChange={(e) => handleInputChange('name', e.target.value)}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-oe-primary focus:border-oe-primary"
                  placeholder="e.g., Main Office, Warehouse, Branch Office"
                />
              </div>

              {/* Address Fields */}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  Address <span className="text-red-500">*</span>
                </label>
                <input
                  type="text"
                  value={formData.address}
                  onChange={(e) => handleInputChange('address', e.target.value)}
                  className={`w-full px-3 py-2 border rounded-lg focus:ring-oe-primary focus:border-oe-primary ${
                    errors.address ? 'border-red-300' : 'border-gray-300'
                  }`}
                  required
                />
                {errors.address && (
                  <p className="mt-1 text-sm text-red-600">{errors.address}</p>
                )}
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  Address Line 2 <span className="text-gray-400">(Optional)</span>
                </label>
                <input
                  type="text"
                  value={formData.address2}
                  onChange={(e) => handleInputChange('address2', e.target.value)}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-oe-primary focus:border-oe-primary"
                  placeholder="Suite, Unit, Floor, etc."
                />
              </div>

              <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">
                    City <span className="text-red-500">*</span>
                  </label>
                  <input
                    type="text"
                    value={formData.city}
                    onChange={(e) => handleInputChange('city', e.target.value)}
                    className={`w-full px-3 py-2 border rounded-lg focus:ring-oe-primary focus:border-oe-primary ${
                      errors.city ? 'border-red-300' : 'border-gray-300'
                    }`}
                    required
                  />
                  {errors.city && (
                    <p className="mt-1 text-sm text-red-600">{errors.city}</p>
                  )}
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">
                    State <span className="text-red-500">*</span>
                  </label>
                  <select
                    value={formData.state}
                    onChange={(e) => handleInputChange('state', e.target.value)}
                    className={`w-full px-3 py-2 border rounded-lg focus:ring-oe-primary focus:border-oe-primary ${
                      errors.state ? 'border-red-300' : 'border-gray-300'
                    }`}
                    required
                  >
                    <option value="">Select State</option>
                    {US_STATES_FORMATTED.map(state => (
                      <option key={state.value} value={state.value}>{state.label}</option>
                    ))}
                  </select>
                  {errors.state && (
                    <p className="mt-1 text-sm text-red-600">{errors.state}</p>
                  )}
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">
                    ZIP Code <span className="text-red-500">*</span>
                  </label>
                  <input
                    type="text"
                    value={formData.zip}
                    onChange={(e) => handleInputChange('zip', e.target.value)}
                    className={`w-full px-3 py-2 border rounded-lg focus:ring-oe-primary focus:border-oe-primary ${
                      errors.zip ? 'border-red-300' : 'border-gray-300'
                    }`}
                    required
                  />
                  {errors.zip && (
                    <p className="mt-1 text-sm text-red-600">{errors.zip}</p>
                  )}
                </div>
              </div>

              {/* AllAboard Group ID override */}
              <div className="border border-gray-200 rounded-lg p-4 bg-gray-50">
                <div className="flex items-center justify-between mb-2">
                  <label className="block text-sm font-medium text-gray-700">
                    AllAboard Group ID Override
                  </label>
                  <label className="flex items-center gap-2 cursor-pointer">
                    <input
                      type="checkbox"
                      checked={formData.overrideAllAboardGroupId}
                      onChange={(e) => {
                        handleInputChange('overrideAllAboardGroupId', e.target.checked);
                        if (!e.target.checked) {
                          handleInputChange('allAboardGroupId', '');
                          setAllAboardGroupIdValidation({});
                        }
                      }}
                      className="rounded border-gray-300 text-oe-primary focus:ring-oe-primary"
                    />
                    <span className="text-sm text-gray-600">Enable override</span>
                  </label>
                </div>
                {formData.overrideAllAboardGroupId && (
                  <div className="space-y-1">
                    <input
                      type="text"
                      value={formData.allAboardGroupId}
                      onChange={(e) => {
                        const v = e.target.value.toLowerCase().replace(/[^a-z0-9-]/g, '');
                        handleInputChange('allAboardGroupId', v);
                        setAllAboardGroupIdValidation({});
                      }}
                      onBlur={async () => {
                        const v = (formData.allAboardGroupId as string).trim();
                        if (!v || v === (location?.AllAboardGroupId || '')) {
                          setAllAboardGroupIdValidation({});
                          return;
                        }
                        setAllAboardGroupIdValidation({ checking: true });
                        const res = await GroupsService.validateLocationGroupId(v, groupId, location?.LocationId);
                        if (res.success && res.data) {
                          setAllAboardGroupIdValidation({
                            available: res.data.available,
                            message: res.data.available
                              ? 'Available'
                              : `Already used by "${res.data.conflictingLocationName || res.data.conflictingLocationId}"`,
                          });
                        } else {
                          setAllAboardGroupIdValidation({ available: false, message: res.message || 'Validation failed' });
                        }
                      }}
                      placeholder="e.g. acme-corp-hq"
                      className="w-full px-3 py-2 border border-gray-300 rounded-lg text-sm font-mono focus:ring-oe-primary focus:border-oe-primary"
                    />
                    <p className="text-xs text-gray-500">Lowercase letters, numbers, and hyphens only.</p>
                    {allAboardGroupIdValidation.checking && (
                      <p className="text-xs text-gray-400">Checking availability…</p>
                    )}
                    {!allAboardGroupIdValidation.checking && allAboardGroupIdValidation.available === true && (
                      <p className="flex items-center gap-1 text-xs text-green-600">
                        <CheckCircle className="h-3.5 w-3.5" /> {allAboardGroupIdValidation.message}
                      </p>
                    )}
                    {!allAboardGroupIdValidation.checking && allAboardGroupIdValidation.available === false && (
                      <p className="flex items-center gap-1 text-xs text-red-600">
                        <AlertCircle className="h-3.5 w-3.5" /> {allAboardGroupIdValidation.message}
                      </p>
                    )}
                  </div>
                )}
                {!formData.overrideAllAboardGroupId && (
                  <p className="text-xs text-gray-400 mt-1">
                    By default, this location inherits the group's AllAboard Master Group ID.
                  </p>
                )}
              </div>

            </div>
          )}

          {/* Contact Tab */}
          {activeTab === 'contact' && (
            <div className="space-y-4">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">
                    Contact Name <span className="text-red-500">*</span>
                  </label>
                  <input
                    type="text"
                    value={formData.contactName}
                    onChange={(e) => handleInputChange('contactName', e.target.value)}
                    className={`w-full px-3 py-2 border rounded-lg focus:ring-oe-primary focus:border-oe-primary ${
                      errors.contactName ? 'border-red-300' : 'border-gray-300'
                    }`}
                    required
                  />
                  {errors.contactName && (
                    <p className="mt-1 text-sm text-red-600">{errors.contactName}</p>
                  )}
                  <p className="text-xs text-gray-500 mt-1">
                    Required for invoice delivery
                  </p>
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">
                    Phone Number
                  </label>
                  <input
                    type="tel"
                    value={formData.contactPhone}
                    onChange={(e) => handleInputChange('contactPhone', e.target.value)}
                    className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-oe-primary focus:border-oe-primary"
                    placeholder="(555) 123-4567"
                  />
                </div>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  Email <span className="text-red-500">*</span>
                </label>
                <input
                  type="email"
                  value={formData.contactEmail}
                  onChange={(e) => handleInputChange('contactEmail', e.target.value)}
                  className={`w-full px-3 py-2 border rounded-lg focus:ring-oe-primary focus:border-oe-primary ${
                    errors.contactEmail ? 'border-red-300' : 'border-gray-300'
                  }`}
                  placeholder="contact@example.com"
                  required
                />
                {errors.contactEmail && (
                  <p className="mt-1 text-sm text-red-600">{errors.contactEmail}</p>
                )}
                <p className="text-xs text-gray-500 mt-1">
                  Required for invoice delivery and billing notifications
                </p>
              </div>
            </div>
          )}

          {/* Payment Methods Tab - Always visible when editing an existing location */}
          {activeTab === 'payment' && location && (
            <div className="space-y-4">
              {/* Payment Billing Option */}
              <div className="bg-blue-50 border border-blue-200 rounded-lg p-4 mb-4">
                <div className="flex items-start">
                  <input
                    type="checkbox"
                    id="useLocationACH"
                    checked={formData.useLocationACH}
                    onChange={(e) => {
                      handleInputChange('useLocationACH', e.target.checked);
                    }}
                    className="h-4 w-4 text-oe-primary focus:ring-oe-primary border-gray-300 rounded mt-1"
                  />
                  <div className="ml-3 flex-1">
                    <label htmlFor="useLocationACH" className="block text-sm font-semibold text-gray-900 cursor-pointer">
                      This location pays for its own members
                    </label>
                    <p className="text-sm text-gray-600 mt-1">
                      {formData.useLocationACH ? (
                        <>
                          <span className="font-medium text-oe-primary-dark">✓ Active:</span> This location will use its own payment methods to pay for member enrollments. 
                          You must have at least 1 active payment method configured below.
                        </>
                      ) : (
                        <>
                          <span className="font-medium text-gray-700">Unchecked:</span> This location's members will be billed using the group's main payment methods 
                          (configured in the <strong>Billing</strong> tab).
                        </>
                      )}
                    </p>
                  </div>
                </div>
              </div>

              {formData.useLocationACH && (
                <>
                  <div className="mb-4">
                    <div className="flex items-center justify-between mb-2">
                      <h4 className="text-sm font-medium text-gray-700">Payment Methods</h4>
                      <button
                        type="button"
                        onClick={() => setPaymentMethodModalOpen(true)}
                        disabled={paymentMethods.filter(m => m.Status === 'Active').length >= 2}
                        className="flex items-center space-x-1 px-3 py-1.5 text-sm border border-gray-300 rounded-md hover:bg-gray-50 text-gray-700 disabled:opacity-50 disabled:cursor-not-allowed"
                      >
                        <Plus className="h-4 w-4" />
                        <span>Add Payment Method</span>
                      </button>
                    </div>
                    <p className="text-xs text-gray-500">
                      Manage payment methods for this location. Maximum of 2 active payment methods allowed. At least 1 is required.
                    </p>
                  </div>
                </>
              )}

              {!formData.useLocationACH && (
                <div className="bg-gray-50 border border-gray-200 rounded-lg p-4">
                  <div className="flex">
                    <Info className="h-5 w-5 text-gray-400 mt-0.5" />
                    <div className="ml-3">
                      <p className="text-sm text-gray-600">
                        Enable <strong>"This location pays for its own members"</strong> above to configure payment methods for this location.
                      </p>
                    </div>
                  </div>
                </div>
              )}

              {formData.useLocationACH && (
                <>
                  {loadingPaymentMethods ? (
                    <div className="flex justify-center py-8">
                      <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-oe-primary"></div>
                    </div>
                  ) : paymentMethods.length === 0 ? (
                    <div className="bg-red-50 border border-red-200 rounded-lg p-4">
                      <div className="flex">
                        <AlertCircle className="h-5 w-5 text-red-600 mt-0.5" />
                        <div className="ml-3">
                          <p className="text-sm font-medium text-red-800">
                            No payment methods on file
                          </p>
                          <p className="text-sm text-red-700 mt-1">
                            <strong>Required:</strong> You must add at least one payment method when this location pays for its own members. 
                            Click "Add Payment Method" above to get started.
                          </p>
                          {errors.paymentMethods && (
                            <p className="text-sm text-red-600 mt-2 font-medium">{errors.paymentMethods}</p>
                          )}
                        </div>
                      </div>
                    </div>
                  ) : (
                    <div className="space-y-3">
                      {paymentMethods.map((method) => (
                        <div key={method.PaymentMethodId} className={`flex items-center justify-between p-4 border rounded-lg ${
                      method.Status === 'Inactive' ? 'border-gray-200 bg-gray-50' : 'border-gray-200'
                    }`}>
                      <div className="flex items-center space-x-3">
                        <div className={`p-2 rounded-lg ${
                          method.Status === 'Inactive' ? 'bg-gray-100' : 'bg-oe-light'
                        }`}>
                          {method.Type === 'ACH' ? (
                            <Building className={`h-5 w-5 ${
                              method.Status === 'Inactive' ? 'text-gray-400' : 'text-oe-primary'
                            }`} />
                          ) : (
                            <CreditCard className={`h-5 w-5 ${
                              method.Status === 'Inactive' ? 'text-gray-400' : 'text-oe-primary'
                            }`} />
                          )}
                        </div>
                        <div className="flex-1">
                          <div className="flex items-center space-x-2">
                            <p className={`text-sm font-medium ${
                              method.Status === 'Inactive' ? 'text-gray-500' : 'text-gray-900'
                            }`}>
                              {getPaymentMethodDisplay(method)}
                            </p>
                            {method.IsDefault && method.Status === 'Active' && (
                              <span className="inline-flex items-center space-x-1 px-2 py-0.5 rounded-full text-xs font-medium bg-blue-100 text-blue-800">
                                <Star className="h-3 w-3" />
                                <span>Primary</span>
                              </span>
                            )}
                            {method.Status === 'Inactive' && (
                              <span className="inline-flex items-center px-2 py-0.5 rounded-full text-xs font-medium bg-gray-100 text-gray-600">
                                Inactive
                              </span>
                            )}
                          </div>
                          <p className={`text-xs mt-1 ${
                            method.Status === 'Inactive' ? 'text-gray-400' : 'text-gray-500'
                          }`}>
                            Added {formatDate(method.CreatedDate)}
                            {method.BillingCity && (
                              <span className="ml-2">• {method.BillingCity}, {method.BillingState}</span>
                            )}
                          </p>
                        </div>
                      </div>
                      
                      <div className="flex items-center space-x-2">
                        {!method.IsDefault && method.Status === 'Active' && (
                          <button
                            type="button"
                            onClick={() => setSetDefaultPaymentMethodConfirm(method.PaymentMethodId)}
                            className="p-2 text-gray-400 hover:text-oe-primary hover:bg-blue-50 rounded-md transition-colors"
                            title="Set as Primary"
                          >
                            <StarOff className="h-4 w-4" />
                          </button>
                        )}
                        
                        <button
                          type="button"
                          onClick={() => setDeletePaymentMethodConfirm(method.PaymentMethodId)}
                          disabled={method.Status === 'Active' && paymentMethods.filter(m => m.Status === 'Active').length === 1}
                          className={`p-2 rounded-md transition-colors ${
                            method.Status === 'Inactive' 
                              ? 'text-gray-300 hover:text-gray-400 hover:bg-gray-100' 
                              : method.Status === 'Active' && paymentMethods.filter(m => m.Status === 'Active').length === 1
                              ? 'text-gray-300 cursor-not-allowed'
                              : 'text-gray-400 hover:text-red-600 hover:bg-red-50'
                          }`}
                          title={
                            method.Status === 'Inactive' 
                              ? 'Remove Payment Method' 
                              : method.Status === 'Active' && paymentMethods.filter(m => m.Status === 'Active').length === 1
                              ? 'You must have at least 1 valid payment method'
                              : 'Delete Payment Method'
                          }
                        >
                          <Trash2 className="h-4 w-4" />
                        </button>
                      </div>
                        </div>
                      ))}
                      
                      {paymentMethods.filter(m => m.Status === 'Active').length >= 2 && (
                        <div className="bg-blue-50 border border-blue-200 rounded-lg p-3">
                          <div className="flex">
                            <Info className="h-4 w-4 text-oe-primary mt-0.5" />
                            <div className="ml-2">
                              <p className="text-sm text-blue-800">
                                Maximum of 2 active payment methods allowed. Remove an existing method to add a new one.
                              </p>
                            </div>
                          </div>
                        </div>
                      )}
                </div>
              )}
                </>
              )}
            </div>
          )}

          {/* Action Buttons */}
          <div className="flex justify-end space-x-3 pt-4 border-t border-gray-200">
            <button
              type="button"
              onClick={onClose}
              className="btn-secondary"
            >
              Cancel
            </button>
            <button
              type="submit"
              disabled={saving}
              className="btn-primary"
            >
              {saving ? 'Saving...' : location ? 'Update Location' : 'Create Location'}
            </button>
          </div>
        </form>

        {/* Payment Method Modal */}
        {location && (
          <LocationPaymentMethodModal
            open={paymentMethodModalOpen}
            onClose={() => setPaymentMethodModalOpen(false)}
            onSave={() => {
              if (location) {
                loadPaymentMethods(location.LocationId);
              }
            }}
            groupId={groupId}
            locationId={location.LocationId}
            showSnackbar={showSnackbar}
          />
        )}

        {/* Delete Payment Method Confirmation */}
        {deletePaymentMethodConfirm && (
          <div 
            className="fixed bg-black bg-opacity-50 flex items-center justify-center z-[10000]" 
            style={{ 
              position: 'fixed', 
              top: 0, 
              left: 0, 
              right: 0, 
              bottom: 0,
              width: '100vw', 
              height: '100vh',
              margin: 0,
              padding: '1rem'
            }}
            onClick={(e) => {
              if (e.target === e.currentTarget) {
                setDeletePaymentMethodConfirm(null);
              }
            }}
          >
            <div className="bg-white rounded-lg max-w-md w-full p-6 shadow-xl" onClick={(e) => e.stopPropagation()}>
              <div className="flex items-center mb-4">
                <AlertCircle className="h-6 w-6 text-red-600" />
                <h3 className="ml-3 text-lg font-medium text-gray-900">Delete Payment Method</h3>
              </div>
              <div className="mb-6">
                <p className="text-sm text-gray-600">
                  Are you sure you want to delete this payment method? This action cannot be undone.
                </p>
              </div>
              <div className="flex justify-end space-x-3">
                <button
                  onClick={() => setDeletePaymentMethodConfirm(null)}
                  className="btn-secondary"
                >
                  Cancel
                </button>
                <button
                  onClick={() => handleDeletePaymentMethod(deletePaymentMethodConfirm)}
                  className="btn-danger"
                >
                  Delete
                </button>
              </div>
            </div>
          </div>
        )}

        {/* Set Default Payment Method Confirmation */}
        {setDefaultPaymentMethodConfirm && (
          <div 
            className="fixed bg-black bg-opacity-50 flex items-center justify-center z-[10000]" 
            style={{ 
              position: 'fixed', 
              top: 0, 
              left: 0, 
              right: 0, 
              bottom: 0,
              width: '100vw', 
              height: '100vh',
              margin: 0,
              padding: '1rem'
            }}
            onClick={(e) => {
              if (e.target === e.currentTarget) {
                setSetDefaultPaymentMethodConfirm(null);
              }
            }}
          >
            <div className="bg-white rounded-lg max-w-md w-full p-6 shadow-xl" onClick={(e) => e.stopPropagation()}>
              <div className="flex items-center mb-4">
                <Info className="h-6 w-6 text-oe-primary" />
                <h3 className="ml-3 text-lg font-medium text-gray-900">Set Primary Payment Method</h3>
              </div>
              <div className="mb-6">
                <p className="text-sm text-gray-600">
                  Set this payment method as the primary payment method for this location?
                </p>
              </div>
              <div className="flex justify-end space-x-3">
                <button
                  onClick={() => setSetDefaultPaymentMethodConfirm(null)}
                  className="btn-secondary"
                >
                  Cancel
                </button>
                <button
                  onClick={() => handleSetDefaultPaymentMethod(setDefaultPaymentMethodConfirm)}
                  className="btn-primary"
                >
                  Set as Primary
                </button>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

// Main Component
const GroupLocationsTab: React.FC<GroupLocationsTabProps> = ({ groupId, groupName }) => {
  const [locations, setLocations] = useState<GroupLocation[]>([]);
  const [loading, setLoading] = useState(true);
  const [showModal, setShowModal] = useState(false);
  const [editingLocation, setEditingLocation] = useState<GroupLocation | null>(null);
  const [deletingLocation, setDeletingLocation] = useState<GroupLocation | null>(null);
  const [setPrimaryLocation, setSetPrimaryLocation] = useState<GroupLocation | null>(null);
  const [snackbar, setSnackbar] = useState<{
    open: boolean;
    message: string;
    severity: 'success' | 'error' | 'info' | 'warning';
  }>({ open: false, message: '', severity: 'info' });

  const showSnackbar = (message: string, severity: 'success' | 'error' | 'info' | 'warning') => {
    setSnackbar({ open: true, message, severity });
  };

  useEffect(() => {
    loadLocations();
  }, [groupId]);

  const loadLocations = async () => {
    try {
      setLoading(true);
      const response = await GroupLocationsService.getLocations(groupId);

      if (response.success && response.data) {
        setLocations(response.data);
      } else {
        throw new Error('Failed to load locations');
      }
    } catch (error) {
      console.error('Error loading locations:', error);
      showSnackbar('Failed to load locations', 'error');
    } finally {
      setLoading(false);
    }
  };

  const handleAddLocation = () => {
    setEditingLocation(null);
    setShowModal(true);
  };

  const handleEditLocation = (location: GroupLocation) => {
    setEditingLocation(location);
    setShowModal(true);
  };

  const handleSetPrimary = async () => {
    if (!setPrimaryLocation) return;

    try {
      const response = await GroupLocationsService.setPrimaryLocation(groupId, setPrimaryLocation.LocationId);

      if (response.success) {
        showSnackbar('Primary location updated successfully', 'success');
        loadLocations();
        setSetPrimaryLocation(null);
      } else {
        throw new Error(response.message || 'Failed to set primary location');
      }
    } catch (error: any) {
      console.error('Error setting primary location:', error);
      showSnackbar(error?.message || 'Failed to set primary location', 'error');
    }
  };

  const handleDeleteLocation = async () => {
    if (!deletingLocation) return;

    try {
      const response = await GroupLocationsService.deleteLocation(groupId, deletingLocation.LocationId);

      if (response.success) {
        showSnackbar('Location deleted successfully', 'success');
        loadLocations();
        setDeletingLocation(null);
      } else {
        throw new Error(response.message || 'Failed to delete location');
      }
    } catch (error: any) {
      console.error('Error deleting location:', error);
      showSnackbar(error?.message || 'Failed to delete location', 'error');
    }
  };

  const formatAddress = (location: GroupLocation): string => {
    const parts = [
      location.Address,
      location.Address2,
      `${location.City}, ${location.State} ${location.Zip}`
    ].filter(Boolean);
    return parts.join(', ');
  };

  if (loading) {
    return (
      <div className="p-6 flex items-center justify-center h-64">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-oe-primary"></div>
      </div>
    );
  }

  return (
    <div className="p-6 space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-2xl font-bold text-oe-neutral-dark">Group Locations</h2>
          <p className="text-gray-600 mt-1">Manage physical work locations for {groupName}</p>
        </div>
        <button
          onClick={handleAddLocation}
          className="btn-primary inline-flex items-center"
        >
          <Plus className="h-4 w-4 mr-2" />
          Add Location
        </button>
      </div>

      {/* Locations Table */}
      {locations.length === 0 ? (
        <div className="bg-white rounded-lg border border-gray-200 p-12 text-center">
          <MapPin className="h-12 w-12 text-gray-400 mx-auto mb-4" />
          <h3 className="text-lg font-medium text-oe-neutral-dark mb-2">No locations added</h3>
          <p className="text-gray-600 mb-4">Get started by adding your first location</p>
          <button
            onClick={handleAddLocation}
            className="btn-primary inline-flex items-center"
          >
            <Plus className="h-4 w-4 mr-2" />
            Add Location
          </button>
        </div>
      ) : (
        <div className="bg-white rounded-lg border border-gray-200 overflow-hidden">
          <div className="overflow-x-auto">
            <table className="min-w-full divide-y divide-gray-200">
              <thead className="bg-oe-neutral-light">
                <tr>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Location
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Address
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Contact
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Payment Method
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Vendor Location IDs
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Status
                  </th>
                  <th className="px-6 py-3 text-right text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Actions
                  </th>
                </tr>
              </thead>
              <tbody className="bg-white divide-y divide-gray-200">
                {locations.map((location) => (
                  <tr key={location.LocationId} className="hover:bg-gray-50">
                    <td className="px-6 py-4 whitespace-nowrap">
                      <div className="flex items-center">
                        <div className="flex-shrink-0 h-10 w-10">
                          <div className="h-10 w-10 rounded-full bg-oe-light flex items-center justify-center">
                            {location.IsPrimary ? (
                              <Star className="h-5 w-5 text-yellow-500 fill-yellow-500" />
                            ) : (
                              <Building2 className="h-5 w-5 text-oe-primary" />
                            )}
                          </div>
                        </div>
                        <div className="ml-4">
                          <div className="flex items-center space-x-2">
                            <div className="text-sm font-medium text-oe-neutral-dark">
                              {location.Name || 'Unnamed Location'}
                            </div>
                            {location.IsPrimary && (
                              <span className="inline-flex items-center px-2 py-0.5 rounded-full text-xs font-medium bg-blue-100 text-blue-800">
                                <Star className="h-3 w-3 mr-1" />
                                Primary
                              </span>
                            )}
                          </div>
                          <div className="text-sm text-gray-500">
                            {location.City}, {location.State}
                          </div>
                        </div>
                      </div>
                    </td>
                    <td className="px-6 py-4">
                      <div className="text-sm text-gray-900">
                        {formatAddress(location)}
                      </div>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <div className="text-sm text-gray-900">
                        {location.ContactName && (
                          <div className="font-medium">{location.ContactName}</div>
                        )}
                        {location.ContactEmail && (
                          <div className="text-gray-500 flex items-center mt-1">
                            <Mail className="h-3 w-3 mr-1" />
                            {location.ContactEmail}
                          </div>
                        )}
                        {location.ContactPhone && (
                          <div className="text-gray-500 flex items-center mt-1">
                            <Phone className="h-3 w-3 mr-1" />
                            {location.ContactPhone}
                          </div>
                        )}
                        {!location.ContactName && !location.ContactEmail && !location.ContactPhone && (
                          <span className="text-gray-400">No contact info</span>
                        )}
                      </div>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <div className="flex flex-col">
                        {location.UseLocationACH ? (
                          <>
                            <div className="flex items-center">
                              <CheckCircle className="h-4 w-4 text-green-600 mr-2" />
                              <span className="text-sm text-gray-900">Location ACH</span>
                            </div>
                            {/* Payment method count could be shown here if we fetch it */}
                          </>
                        ) : (
                          <>
                            <div className="flex items-center">
                              <Building2 className="h-4 w-4 text-oe-primary mr-2" />
                              <span className="text-sm text-gray-900">Group Account</span>
                            </div>
                          </>
                        )}
                      </div>
                    </td>
                    <td className="px-6 py-4">
                      {location.VendorLocationIds && location.VendorLocationIds.length > 0 ? (
                        <div className="space-y-1">
                          {location.VendorLocationIds.map((v) => (
                            <div key={v.VendorId} className="flex items-center gap-1">
                              <span className="text-xs text-gray-500 shrink-0">Vendor:</span>
                              <span className="text-xs font-medium text-gray-900 font-mono">{v.VendorLocationId}</span>
                            </div>
                          ))}
                        </div>
                      ) : (
                        <span className="text-xs text-gray-400">—</span>
                      )}
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <span className={`inline-flex px-2 py-1 text-xs font-semibold rounded-full ${
                        location.Status === 'Active' 
                          ? 'bg-green-100 text-green-800' 
                          : location.Status === 'Inactive'
                          ? 'bg-yellow-100 text-yellow-800'
                          : 'bg-gray-100 text-gray-800'
                      }`}>
                        {location.Status}
                      </span>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                      <div className="flex items-center justify-end space-x-2">
                        {!location.IsPrimary && location.Status === 'Active' && (
                          <button
                            onClick={() => setSetPrimaryLocation(location)}
                            className="text-oe-primary hover:text-oe-primary-dark transition-colors"
                            title="Set as primary location"
                          >
                            <StarOff className="h-4 w-4" />
                          </button>
                        )}
                        <button
                          onClick={() => handleEditLocation(location)}
                          className="text-oe-primary hover:text-oe-dark transition-colors"
                          title="Edit location"
                        >
                          <Edit className="h-4 w-4" />
                        </button>
                        <button
                          onClick={() => setDeletingLocation(location)}
                          disabled={location.IsPrimary && locations.filter(l => l.Status === 'Active').length === 1}
                          className={`transition-colors ${
                            location.IsPrimary && locations.filter(l => l.Status === 'Active').length === 1
                              ? 'text-gray-300 cursor-not-allowed'
                              : 'text-red-600 hover:text-red-700'
                          }`}
                          title={
                            location.IsPrimary && locations.filter(l => l.Status === 'Active').length === 1
                              ? 'Cannot delete the only location'
                              : location.IsPrimary
                              ? 'Cannot delete primary location. Set another location as primary first.'
                              : 'Delete location'
                          }
                        >
                          <Trash2 className="h-4 w-4" />
                        </button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {/* Location Modal */}
      <LocationModal
        open={showModal}
        onClose={() => {
          setShowModal(false);
          setEditingLocation(null);
        }}
        location={editingLocation}
        onSave={loadLocations}
        groupId={groupId}
        showSnackbar={showSnackbar}
      />

      {/* Set Primary Location Confirmation Modal */}
      {setPrimaryLocation && (
        <div 
          className="fixed bg-black bg-opacity-50 flex items-center justify-center z-[9999]" 
          style={{ 
            position: 'fixed', 
            top: 0, 
            left: 0, 
            right: 0, 
            bottom: 0, 
            width: '100vw', 
            height: '100vh',
            margin: 0,
            padding: '1rem'
          }}
          onClick={(e) => {
            if (e.target === e.currentTarget) {
              setSetPrimaryLocation(null);
            }
          }}
        >
          <div className="bg-white rounded-lg max-w-md w-full p-6 shadow-xl" onClick={(e) => e.stopPropagation()}>
            <div className="flex items-center mb-4">
              <div className="flex-shrink-0">
                <Star className="h-6 w-6 text-oe-primary" />
              </div>
              <h3 className="ml-3 text-lg font-medium text-gray-900">Set Primary Location</h3>
            </div>
            <div className="mb-6">
              <p className="text-sm text-gray-600">
                Set this location as the primary location for the group? This will change the primary location from the current one.
              </p>
              {setPrimaryLocation.Name && (
                <p className="mt-2 text-sm font-medium text-gray-900">
                  Location: {setPrimaryLocation.Name}
                </p>
              )}
            </div>
            <div className="flex justify-end space-x-3">
              <button
                onClick={() => setSetPrimaryLocation(null)}
                className="btn-secondary"
              >
                Cancel
              </button>
              <button
                onClick={handleSetPrimary}
                className="btn-primary"
              >
                Set as Primary
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Delete Confirmation Modal */}
      {deletingLocation && (
        <div 
          className="fixed bg-black bg-opacity-50 flex items-center justify-center z-[9999]" 
          style={{ 
            position: 'fixed', 
            top: 0, 
            left: 0, 
            right: 0, 
            bottom: 0, 
            width: '100vw', 
            height: '100vh',
            margin: 0,
            padding: '1rem'
          }}
          onClick={(e) => {
            if (e.target === e.currentTarget) {
              setDeletingLocation(null);
            }
          }}
        >
          <div className="bg-white rounded-lg max-w-md w-full p-6 shadow-xl" onClick={(e) => e.stopPropagation()}>
            <div className="flex items-center mb-4">
              <div className="flex-shrink-0">
                <AlertCircle className="h-6 w-6 text-red-600" />
              </div>
              <h3 className="ml-3 text-lg font-medium text-gray-900">Delete Location</h3>
            </div>
            <div className="mb-6">
              <p className="text-sm text-gray-600">
                Are you sure you want to delete this location? This action cannot be undone.
              </p>
              {deletingLocation.Name && (
                <p className="mt-2 text-sm font-medium text-gray-900">
                  Location: {deletingLocation.Name}
                </p>
              )}
              {deletingLocation.IsPrimary && (
                <div className="mt-3 p-3 bg-red-50 border border-red-200 rounded-lg">
                  <p className="text-sm text-red-800 font-medium">
                    This is the primary location. Please set another location as primary before deleting.
                  </p>
                </div>
              )}
            </div>
            <div className="flex justify-end space-x-3">
              <button
                onClick={() => setDeletingLocation(null)}
                className="btn-secondary"
              >
                Cancel
              </button>
              <button
                onClick={handleDeleteLocation}
                className="btn-danger"
              >
                Delete Location
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Snackbar */}
      <Snackbar
        open={snackbar.open}
        message={snackbar.message}
        severity={snackbar.severity}
        onClose={() => setSnackbar({ ...snackbar, open: false })}
      />
    </div>
  );
};

export default GroupLocationsTab;

