/**
 * Alert Emailer
 *
 * Sends a SendGrid email for Priority 1 (critical) findings
 * to the configured ALERT_EMAIL address.
 */

const sgMail = require('@sendgrid/mail');

/**
 * Send an alert email summarizing all Priority 1 findings from a run.
 *
 * @param {Array} criticalFindings - [{appServiceName, title, summary, recommendation, category}, ...]
 * @param {string} runId
 * @param {Function} log
 */
async function sendCriticalAlert(criticalFindings, runId, log) {
  if (!criticalFindings || criticalFindings.length === 0) return;

  const apiKey = process.env.SENDGRID_API_KEY;
  if (!apiKey) {
    log('SENDGRID_API_KEY not set — skipping alert email');
    return;
  }

  const alertEmail = process.env.ALERT_EMAIL || 'jeremy@mightywell.us';
  const fromEmail = process.env.DEFAULT_FROM_EMAIL || 'noreply@allaboard365.com';

  sgMail.setApiKey(apiKey);

  const findingsHtml = criticalFindings.map((f, i) => `
    <tr style="border-bottom:1px solid #e5e7eb;">
      <td style="padding:12px;vertical-align:top;">
        <strong style="color:#dc2626;">${escapeHtml(f.title)}</strong><br/>
        <span style="color:#6b7280;font-size:13px;">${escapeHtml(f.appServiceName)} &bull; ${escapeHtml(f.category || 'Error')}</span>
      </td>
    </tr>
    <tr style="border-bottom:2px solid #e5e7eb;">
      <td style="padding:8px 12px 16px 12px;">
        <p style="margin:0 0 8px 0;color:#374151;">${escapeHtml(f.summary)}</p>
        ${f.recommendation ? `<p style="margin:0;color:#1d4ed8;font-size:13px;"><strong>Recommendation:</strong> ${escapeHtml(f.recommendation)}</p>` : ''}
      </td>
    </tr>
  `).join('');

  const html = `
    <div style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;max-width:640px;margin:0 auto;">
      <div style="background:#dc2626;color:#fff;padding:16px 24px;border-radius:8px 8px 0 0;">
        <h2 style="margin:0;font-size:18px;">AI Inspector — Critical Alert</h2>
        <p style="margin:4px 0 0;font-size:13px;opacity:0.9;">${criticalFindings.length} critical finding(s) detected</p>
      </div>
      <div style="border:1px solid #e5e7eb;border-top:none;border-radius:0 0 8px 8px;overflow:hidden;">
        <table style="width:100%;border-collapse:collapse;">
          ${findingsHtml}
        </table>
        <div style="padding:16px 12px;background:#f9fafb;font-size:12px;color:#6b7280;">
          Run ID: ${escapeHtml(runId)}<br/>
          Generated by AI Inspector &bull; AllAboard365
        </div>
      </div>
    </div>
  `;

  const appNames = [...new Set(criticalFindings.map((f) => f.appServiceName))].join(', ');
  const subject = `[CRITICAL] AI Inspector: ${criticalFindings.length} issue(s) on ${appNames}`;

  const msg = {
    to: alertEmail,
    from: fromEmail,
    subject,
    html,
    text: criticalFindings.map((f) =>
      `[${f.appServiceName}] ${f.title}\n${f.summary}\nRecommendation: ${f.recommendation || 'N/A'}\n`
    ).join('\n---\n\n') + `\nRun ID: ${runId}`,
  };

  try {
    await sgMail.send(msg);
    log(`Alert email sent to ${alertEmail} — ${criticalFindings.length} critical finding(s)`);
  } catch (err) {
    log(`Failed to send alert email: ${err.message}`);
    if (err.response?.body) {
      log(`SendGrid response: ${JSON.stringify(err.response.body)}`);
    }
  }
}

function escapeHtml(str) {
  if (!str) return '';
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

module.exports = { sendCriticalAlert };
