// hooks/admin/useGroupLocationVendorIds.ts
// CRUD + generate for per-location vendor IDs within a group+vendor combination

import { useCallback, useEffect, useState } from 'react';
import { apiService } from '../../services/api.service';

export interface LocationVendorId {
  LocationId: string;
  LocationName: string;
  VendorLocationId: string | null;
  IsAutoGenerated: boolean;
}

export interface GeneratePreviewItem {
  LocationId: string;
  LocationName: string;
  proposedVendorLocationId: string;
  alreadyExists: boolean;
  idInUse: boolean;
}

export interface GenerateApplyResult {
  created: number;
  errors: string[];
}

interface UseGroupLocationVendorIdsResult {
  locationIds: LocationVendorId[];
  loading: boolean;
  refresh: () => void;

  /** Preview what generate would create — returns preview rows */
  previewGenerate: () => Promise<GeneratePreviewItem[]>;
  /** Apply the generated IDs */
  applyGenerate: () => Promise<GenerateApplyResult>;

  /** Manually set a single location's vendor ID */
  updateLocationId: (locationId: string, vendorLocationId: string) => Promise<void>;
}

export function useGroupLocationVendorIds(
  groupId: string,
  vendorId: string
): UseGroupLocationVendorIdsResult {
  const [locationIds, setLocationIds] = useState<LocationVendorId[]>([]);
  const [loading, setLoading] = useState(false);

  const fetch = useCallback(async () => {
    if (!groupId || !vendorId) return;
    setLoading(true);
    try {
      const res = await apiService.get<{ success: boolean; data: LocationVendorId[] }>(
        `/api/vendor-group-ids/group/${groupId}/vendor/${vendorId}/location-ids`
      );
      if (res?.success && Array.isArray(res.data)) {
        setLocationIds(res.data);
      } else {
        setLocationIds([]);
      }
    } catch {
      setLocationIds([]);
    } finally {
      setLoading(false);
    }
  }, [groupId, vendorId]);

  useEffect(() => {
    fetch();
  }, [fetch]);

  const previewGenerate = useCallback(async (): Promise<GeneratePreviewItem[]> => {
    const res = await apiService.get<{ success: boolean; data: GeneratePreviewItem[] }>(
      `/api/vendor-group-ids/group/${groupId}/vendor/${vendorId}/location-ids/generate`
    );
    if (res?.success && Array.isArray(res.data)) {
      return res.data;
    }
    return [];
  }, [groupId, vendorId]);

  const applyGenerate = useCallback(async (): Promise<GenerateApplyResult> => {
    const res = await apiService.post<{ success: boolean; data: GenerateApplyResult }>(
      `/api/vendor-group-ids/group/${groupId}/vendor/${vendorId}/location-ids/generate`,
      {}
    );
    if (res?.success && res.data) {
      await fetch();
      return res.data;
    }
    return { created: 0, errors: [] };
  }, [groupId, vendorId, fetch]);

  const updateLocationId = useCallback(
    async (locationId: string, vendorLocationId: string) => {
      await apiService.put(
        `/api/vendor-group-ids/group/${groupId}/location/${locationId}/vendor/${vendorId}/vendor-location-id`,
        { vendorLocationId }
      );
      await fetch();
    },
    [groupId, vendorId, fetch]
  );

  return {
    locationIds,
    loading,
    refresh: fetch,
    previewGenerate,
    applyGenerate,
    updateLocationId,
  };
}
