/**
 * Route tests for groupLocations.js:
 *  - GET /:groupId/locations includes VendorLocationIds per location
 *  - POST /:groupId/locations triggers autoGenerateForNewLocation fire-and-forget
 */

// ---- Auth middleware mock ----
// authorize is a factory; requireTenantAccess is used directly as middleware
jest.mock('../../middleware/auth', () => ({
    authorize: () => (_req, _res, next) => next(),
    requireTenantAccess: (_req, _res, next) => next(),
    getUserRoles: jest.fn(() => ['SysAdmin']),
    optionalAuth: (_req, _res, next) => next(),
}));

// ---- agentGroupAccess mock ----
jest.mock('../../utils/agentGroupAccess', () => ({
    getAccessibleAgentIdsForUser: jest.fn().mockResolvedValue([]),
    buildAgentScopeClause: jest.fn(() => '1=1'),
}));

// ---- PaymentMethodService mock ----
jest.mock('../../services/PaymentMethodService', () => ({
    ensureDimeCustomer: jest.fn(),
    validatePaymentMethodData: jest.fn(),
    createPaymentMethod: jest.fn(),
    insertPaymentMethod: jest.fn(),
    updatePaymentMethodDefaults: jest.fn(),
}));

// ---- VendorGroupIdService mock ----
jest.mock('../../services/vendorGroupIdService');

// ---- DB mock ----
const mockInput = jest.fn().mockReturnThis();
let mockQueryResponses = [];
let mockQueryCallIndex = 0;
const mockQuery = jest.fn().mockImplementation(() => {
    const response = mockQueryResponses[mockQueryCallIndex++] || { recordset: [], rowsAffected: [1] };
    return Promise.resolve(response);
});
const mockRequest = jest.fn(() => ({ input: mockInput, query: mockQuery }));
const mockPool = { request: mockRequest };

jest.mock('../../config/database', () => ({
    getPool: jest.fn(async () => mockPool),
    sql: {
        UniqueIdentifier: 'UniqueIdentifier',
        NVarChar: jest.fn((n) => `NVarChar(${n})`),
        Int: 'Int',
        Bit: 'Bit',
        VarChar: 'VarChar',
        MAX: 'MAX',
        DateTime2: 'DateTime2',
    },
}));
jest.mock('mssql', () => ({
    UniqueIdentifier: 'UniqueIdentifier',
    NVarChar: jest.fn((n) => `NVarChar(${n})`),
    Int: 'Int',
    Bit: 'Bit',
    VarChar: 'VarChar',
    MAX: 'MAX',
    DateTime2: 'DateTime2',
}));

const request = require('supertest');
const express = require('express');
const groupLocationsRouter = require('../groupLocations');
const VendorGroupIdService = require('../../services/vendorGroupIdService');

const TENANT_ID = 'ffffffff-ffff-ffff-ffff-ffffffffffff';
const GROUP_ID  = 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb';
const LOC_ID_1  = 'cccccccc-cccc-cccc-cccc-cccccccccccc';
const LOC_ID_2  = 'dddddddd-dddd-dddd-dddd-dddddddddddd';
const VENDOR_ID = 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa';
const USER_ID   = 'eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee';

function makeApp() {
    const app = express();
    app.use(express.json());
    app.use((req, _res, next) => {
        req.user = {
            UserId: USER_ID,
            TenantId: TENANT_ID,
            userType: 'SysAdmin',
            currentRole: 'SysAdmin',
            roles: ['SysAdmin'],
        };
        next();
    });
    app.use('/api/groups', groupLocationsRouter);
    return app;
}

function setQueryResponses(...responses) {
    mockQueryCallIndex = 0;
    mockQueryResponses = responses;
}

beforeEach(() => {
    jest.clearAllMocks();
    mockQueryCallIndex = 0;
    mockQueryResponses = [];
});

// ----------------------------------------------------------------
// GET /:groupId/locations — includes VendorLocationIds
// ----------------------------------------------------------------
describe('GET /api/groups/:groupId/locations — vendor location IDs', () => {
    test('200 with VendorLocationIds attached to each location', async () => {
        setQueryResponses(
            // verifyGroupAccess (SysAdmin path) — groups check
            { recordset: [{ GroupId: GROUP_ID, TenantId: TENANT_ID, AgentId: null }] },
            // locations list
            { recordset: [
                { LocationId: LOC_ID_1, GroupId: GROUP_ID, Name: 'HQ',    Status: 'Active' },
                { LocationId: LOC_ID_2, GroupId: GROUP_ID, Name: 'Branch', Status: 'Active' },
            ]},
            // vendor location IDs batch fetch
            { recordset: [
                { LocationId: LOC_ID_1, VendorId: VENDOR_ID, VendorLocationId: 'MW1000', IsAutoGenerated: true, VendorName: 'Test Vendor' },
                { LocationId: LOC_ID_2, VendorId: VENDOR_ID, VendorLocationId: 'MW1001', IsAutoGenerated: true, VendorName: 'Test Vendor' },
            ]},
        );

        const res = await request(makeApp()).get(`/api/groups/${GROUP_ID}/locations`);

        expect(res.status).toBe(200);
        expect(res.body.success).toBe(true);
        const locs = res.body.data;
        expect(locs).toHaveLength(2);

        const hq = locs.find(l => l.LocationId === LOC_ID_1);
        expect(hq).toBeDefined();
        expect(Array.isArray(hq.VendorLocationIds)).toBe(true);
        expect(hq.VendorLocationIds[0].VendorLocationId).toBe('MW1000');
    });

    test('200 with empty VendorLocationIds when none configured', async () => {
        setQueryResponses(
            { recordset: [{ GroupId: GROUP_ID, TenantId: TENANT_ID }] },
            { recordset: [
                { LocationId: LOC_ID_1, GroupId: GROUP_ID, Name: 'HQ', Status: 'Active' },
            ]},
            { recordset: [] }, // no vendor location IDs
        );

        const res = await request(makeApp()).get(`/api/groups/${GROUP_ID}/locations`);

        expect(res.status).toBe(200);
        const hq = res.body.data[0];
        expect(hq.VendorLocationIds).toEqual([]);
    });
});

// ----------------------------------------------------------------
// POST /:groupId/locations — auto-generates location vendor IDs
// ----------------------------------------------------------------
describe('POST /api/groups/:groupId/locations — auto-generate vendor location IDs', () => {
    const validBody = {
        address: '123 Main St',
        city: 'Springfield',
        state: 'IL',
        zip: '62701',
        contactName: 'John Smith',
        contactEmail: 'john@example.com',
    };

    test('400 when required address fields are missing', async () => {
        const res = await request(makeApp())
            .post(`/api/groups/${GROUP_ID}/locations`)
            .send({ contactName: 'Test', contactEmail: 'test@test.com' });
        expect(res.status).toBe(400);
    });

    test('400 when contactName is missing', async () => {
        const res = await request(makeApp())
            .post(`/api/groups/${GROUP_ID}/locations`)
            .send({ address: '123 Main', city: 'Springfield', state: 'IL', zip: '62701', contactEmail: 'test@test.com' });
        expect(res.status).toBe(400);
    });

    test('201 on successful create and calls autoGenerateForNewLocation fire-and-forget', async () => {
        VendorGroupIdService.autoGenerateForNewLocation.mockResolvedValue({ success: true, created: 1 });

        setQueryResponses(
            // verifyGroupAccess
            { recordset: [{ GroupId: GROUP_ID, TenantId: TENANT_ID }] },
            // locationCount query
            { recordset: [{ locationCount: 1 }] },
            // INSERT (rowsAffected only, no recordset)
            { recordset: [], rowsAffected: [1] },
            // fetch created location
            { recordset: [{ LocationId: LOC_ID_1, GroupId: GROUP_ID, Name: null, Status: 'Active' }] },
            // getTenantId for auto-generate
            { recordset: [{ TenantId: TENANT_ID }] },
        );

        const res = await request(makeApp())
            .post(`/api/groups/${GROUP_ID}/locations`)
            .send(validBody);

        expect(res.status).toBe(201);
        expect(res.body.success).toBe(true);

        // Fire-and-forget: give it a tick to call
        await new Promise(r => setTimeout(r, 20));
        expect(VendorGroupIdService.autoGenerateForNewLocation).toHaveBeenCalledWith(
            GROUP_ID, expect.any(String), TENANT_ID, USER_ID
        );
    });

    test('201 still succeeds even if autoGenerateForNewLocation throws', async () => {
        VendorGroupIdService.autoGenerateForNewLocation.mockRejectedValue(new Error('DB timeout'));

        setQueryResponses(
            { recordset: [{ GroupId: GROUP_ID, TenantId: TENANT_ID }] },
            { recordset: [{ locationCount: 0 }] },
            { recordset: [], rowsAffected: [1] },
            { recordset: [{ LocationId: LOC_ID_1, GroupId: GROUP_ID, Status: 'Active' }] },
            { recordset: [{ TenantId: TENANT_ID }] },
        );

        const res = await request(makeApp())
            .post(`/api/groups/${GROUP_ID}/locations`)
            .send(validBody);

        expect(res.status).toBe(201);
    });
});
